### ISSUE TITLE
[Suggestion] Dimensional locks/whitelisting

### ISSUE THREAD

**Issue by CritFlaw** [TheCBProject/EnderStorage#100]
I'm making a pack in which I want to separate the resource gen you have access to in one dim from the other. Skyblock has ex nihilo, overworld does not. It would be very useful to have the ability to not allow two dimensions to send items/liquids from/to each other.

**Comment by Ecu** [comment]
I would have to say that you should not use Ender Storage then.  Ender Storage is item/liquid storage that exists simultaneously in multiple locations.  So it isn't teleportation, but that the chest gives you access to the that shared storage.  I feel it is out of the scope of the mod to separate the storage further by dimension.

**Comment by CritFlaw** [comment]
Ah, fair enough.
