### ISSUE TITLE
Crash with potion core when looking at ender-linked tank

### ISSUE THREAD

**Issue by Luke616** [TheCBProject/EnderStorage#101]
Hello,

Having an odd crash in a multiplayer server with enderstorage and potion core installed. This crash occurred when placing an ender-linked tank next to a resourceful furnace from industrial foregoing. It immediately crashed my client, and crashed anyone else who looked at the tank. The server itself did not crash and players who did not look at the tank remained unaffected. Upon trying to log in after the initial crash, I would immediately crash again. I have not been able to replicate this in single player.
https://pastebin.com/6VjX0TPy

I'll cross post this to the potion core github as well

Thanks!

Versions:
Minecraft 1.12.2
Forge 14.23.5.2807
CodeChickenLib 3.2.2.353
EnderStorage 2.4.5.135
PotionCore 1.6

**Comment by Luke616** [comment]
Just cross-posted this to the potion core issue tracker here:
https://minecraft.curseforge.com/projects/potion-core/issues/4

**Comment by covers1624** [comment]
This is literelly impossible unless you have world corruption.
