### ISSUE TITLE
[Suggestion] Auto-Pickup w/ filter

### ISSUE THREAD

**Issue by AMartinie** [TheCBProject/EnderStorage#103]
Currently there isn't a mod that can both auto-pickup by filter, and also transport said items elsewhere in the world. Thermal Satchels have one of the best filtering systems, but you can't automate the extraction of those items while you're out exploring. With an ender bag tied to an ender chest, and then chunkloading the ender chest, you can automatically extract those items. Unfortunately the best method available at the moment is to auto-pickup items with thermal satchels and then take a break to put the items into the EnderStorage bag. I considered submitting a PR to IronBackpacks or Thermal for similar functionality to EnderStorage but after reviewing the code, I believe adding an auto-pickup/filter capability to EnderStorage is the best option that is currently available.

**Comment by Ecu** [comment]
No.
