### ISSUE TITLE
Tanks insert on opposite side of Thermal Machines

### ISSUE THREAD

**Issue by MindCaged** [TheCBProject/EnderStorage#104]
Okay, I've noticed a bug between Thermal and EnderStorage. If you place an ender tank next to a thermal machine, and set it to auto output. You need to set the opposite side of the thermal machine to input.

Example:
  Ender Tank on South side of Thermal machine set to auto output. For the Thermal machine to accept the input you need to set the North side to allow input. Same with top/bottom, if you put it on the top, you need to set the bottom of the thermal machine to input. I've seen this in both the Ultimate Alchemy pack as well as in Enigmatica 2 Expert.

**Comment by gigabit101** [comment]
Can you confirm if this is still an issue with the latest versions of the mods?

**Comment by covers1624** [comment]
Cannot reproduce this.
