### ISSUE TITLE
Piston problem

### ISSUE THREAD

**Issue by Flamabletheone** [TheCBProject/EnderStorage#106]
When i pushed the end chest with a piston it stopped my game, didn't crash but minecraft became completely unplayable. Ended up force closing it. This has happened to me twice so it wasn't a one off bug. Also when re-logging the end chest was pushed. Would it be possible to leave it with the ability to be pushed? Thanks! 

![2019-05-16_15 47 55](https://user-images.githubusercontent.com/50692224/57830610-f5709600-77f5-11e9-9f15-25139e68b33c.png)

**Comment by gigabit101** [comment]
Ender chests are not meant to be moved with pistons, This is an issue because of another mod allowing this to happen.
