### ISSUE TITLE
Owner is a playername?

### ISSUE THREAD

**Issue by elementalistic** [TheCBProject/EnderStorage#107]
Looking at the NBT data of an Ender Tank, it shows up as "owner: 'name'" with F3+H.  The problem with with this is if a user changes their name, for example the /nick command in ftbutils, or even changes their name through the mojang site.  This will then mean they lose access to it as it's not theirs.

It should be using the players UUID.

**Comment by Caraxi** [comment]
#108 will avoid nicknames being used. Isn't ideal not using uuid, but less changes required.

**Comment by gigabit101** [comment]
This will be done for 1.13+
