### ISSUE TITLE
Ender Chests and Ender Tanks don't render when thrown on the ground as items

### ISSUE THREAD

**Issue by aaronhowser1** [TheCBProject/EnderStorage#110]
![image](https://user-images.githubusercontent.com/15698722/62248976-feaddf80-b3ae-11e9-999b-352921d2ab12.png)

**Comment by covers1624** [comment]
Do translocators render when thrown? What about DE MobSouls? ThermalExpansion Strong boxes? ThermalDynamics Facades?

**Comment by aaronhowser1** [comment]
I don't have Translocators, but the others don't render when thrown either so I suppose this isn't an EnderStorage issue. Do you know what mod it *is* an issue with so I can take it up with them?

**Comment by covers1624** [comment]
Sadly its bad interaction from another mod with CCL, You will have to strip down the pack untill you find the culprit.

**Comment by NixTheFae** [comment]
I thought I would mention this. I came across this bug in my pack and was able to resolve it by adding the brandon's core mod to my mod folder
