### ISSUE TITLE
Ender Storage Chests Disconnect All Non-Host Clients When Opened

### ISSUE THREAD

**Issue by VaelophisNyx** [TheCBProject/EnderStorage#111]
As the title says, any clients connected to a multiplayer server (in this case, LAN based), disconnect when an ender chest is opened anywhere in the world, regardless of the inventory of the chest. Buildcraft piping allows adding/removing items normally, however.

Log files will be provided in a little while, when I can get them off the client(s) who disconnect when it opens.

most recent version of the mod is installed, from Curseforge, running on 1.12.2, with the most recent version of the required library also installed and enabled.

**Comment by VaelophisNyx** [comment]
Additional information: It seems to only happen when it's a chest connected to one in a chunk currently loaded by a ChickenChunks loader. This was just made apparent to me as I opened a chest with a different inventory with no chests outside player-loaded chunks and they did not disconnect. I, however, opened one in a non-player loaded chunk and it did cause a disconnect.

EDIT: Also seems to happen with -any- instance of chest W-W-W, even if it's the only one.

**Comment by VaelophisNyx** [comment]
Log file was worthless, it simply cuts out at the disconnect, not even recording a disconnection.

**Comment by pabthelamb** [comment]
Happening to me too.

**Comment by pabthelamb** [comment]
what mods do you have?

**Comment by pabthelamb** [comment]
Seems to be related to Code Chicken Lib as downgrading Ender Storage doesn't fix it but downgrading to the previous version of Code Chicken Lib does.

**Comment by covers1624** [comment]
Waiting on result of https://github.com/TheCBProject/CodeChickenLib/pull/258

**Comment by covers1624** [comment]
https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8/files/2779848
Should fix the problem
