### ISSUE TITLE
Please name the ID from the Ender Chest back to "enderstorage:enderchest" from enderstorage:ender_storage"

### ISSUE THREAD

**Issue by VerryMan** [TheCBProject/EnderStorage#112]
I know a program for mining turtles from "Computercraft" mod.
The owner of the mining program is inactive and has support for your mod, but he has written down "enderstorage:enderchest" in his code and you can't change it because it will auto download the original code with every start.. Would be pretty kind of you if you changed it back to the previous ID.

**Comment by covers1624** [comment]
lolno that's not possible. I'm not changing my ID's because someone else has outdated stuff.

**Comment by KingLemming** [comment]
Crazy idea, you could write your own program for Computercraft.
