### ISSUE TITLE
display name changes interfere with chest linking

### ISSUE THREAD

**Issue by LincT** [TheCBProject/EnderStorage#113]
There are a few mods that change one's display name. When this is changed, it tends to interfere with successfully linking ender chests (not ender pouches, sicne those copy the data from )

The mod from this instance of the issue was more player models. (which stores a display name in the player nbt data). This issue might be reproduceable if one changes their player name through traditional means as well

I haven't dug into the code yet, but I was thinking a fix for this might be to link chests via uuid of the player, and to query the server for the player name to display if that was possible?

Steps to reproduce:
 (requires more player models for 1.12 installed)
1) place an ender chest
2) lock it with a diamond
3) place another ender chest of the same color combination
4) use ./mpm name <type any other name here>
5) lock second chest with diamond
6) place item in either chest, it will not transfer to the other

**Comment by covers1624** [comment]
Fixed in 1.14 port, not being backported.
