### ISSUE TITLE
Players able to unlock and change colors on locked chest that they do not own

### ISSUE THREAD

**Issue by LincT** [TheCBProject/EnderStorage#114]
While playing 1.12, I found it was possible to shift + rightclick to remove a diamond from a chest that another player was the named owner of. 

Steps to reproduce:
1) place and ender chest
2) lock chest with a diamond
3) have another player on the same server shift + rightclick on the diamond latch

**Comment by covers1624** [comment]
Right, its not intended to be protection against people but a separate channel network.
