### ISSUE TITLE
[question/cuggestion] support for custom dyes

### ISSUE THREAD

**Issue by yukinagatosc2** [TheCBProject/EnderStorage#117]
If I wanted to add a custom item that acted like a dye, would it be possible to add support for that dye in ender chest codes?

**Comment by covers1624** [comment]
If your item is OreDictionaried as dye, it will just work fine.

**Comment by yukinagatosc2** [comment]
These items are in the dye ore dictionary but they're not being treated as dyes by the enderchest.
