### ISSUE TITLE
[Suggestion] Numbers instead colors

### ISSUE THREAD

**Issue by jk1895** [TheCBProject/EnderStorage#118]
Any chance we can have numbers on the chests instead colors? Like a lock on a briefcase with three digits. Maybe optional as an option in the config file?
That would be awesome!
Thank you!

**Comment by Ecu** [comment]
No.

**Comment by covers1624** [comment]
Yeah, this won't be happening. Dyes are just simpler, and technically, you would have fewer channels if it were to use digits.
