### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by TheSaucyWelshman** [TheCBProject/EnderStorage#119]
https://hastebin.com/vojiqeveme.rb

I've had this issue in the past and temporarily fixed it by closing my text editor (Sublime Text 3) during startup but now it's happening even without the editor open.

**Comment by covers1624** [comment]
Welcome to windows where programs can lock files and cause issues for other programs. Try closing everything, make sure no sublime processes are running eith task manager, if that doesn't work, reboot.
