### ISSUE TITLE
Not so much an issue then a question.

### ISSUE THREAD

**Issue by CarlucciMods** [TheCBProject/EnderStorage#120]
Anyway I can decompile this mod to get it to work for 1.14.4

I have a server and alot of people wanting to use this awsome mod. 

Unless your working on this for 1.14.4. in which i would say, thank you.

**Comment by covers1624** [comment]
(Whops thought this was an issue on NEI), A port for 1.14 is being worked on, got caught up with stuff over the holidays. Gonna get back to work on stuff soon.
