### ISSUE TITLE
Not in Gzip Format --- Fix

### ISSUE THREAD

**Issue by mahenderson2010** [TheCBProject/EnderStorage#122]
Hello I recently ran into a problem with Ender Storage where it crashed my minecraft on startup of the world. I had found your post here that had said that the only fix you knew of at the time was to delete the mod file or start over. I did some digging and found that if you delete the .dat files in the save that is being affected it fixes the issue with out have to delete the mod. I hope this helps and have a good day!

Link to the Crash report:
https://paste.dimdev.org/qumiqahihu.mccrash

**Comment by covers1624** [comment]
You need to delete the `EnderStorage` folder from your world folder.
