### ISSUE TITLE
crash report antimatter chemistry

### ISSUE THREAD

**Issue by ssennz** [TheCBProject/EnderStorage#124]
[crash-2020-04-10_13.53.40-server.txt](https://github.com/TheCBProject/EnderStorage/files/4461417/crash-2020-04-10_13.53.40-server.txt)

**Comment by covers1624** [comment]
Your ender storage data is corrupt, do as it says and delete the `EnderStorage` folder in your world.

**Comment by ssennz** [comment]
thanks, i will try
