### ISSUE TITLE
[1.15.2] Crash with Ender Storage and Economic Inc

### ISSUE THREAD

**Issue by realTIMematrix** [TheCBProject/EnderStorage#127]
Hi,

the game crashed and I don't know which mod produce the issue. I can only see that both mods together doesn't work.

Using:

- Forge: 31.2.0
- jei-1.15.2-6.0.0.4.jar
- EnderStorage-1.15.2-2.5.0.143-universal.jar
- CodeChickenLib-1.15.2-3.3.0.373-universal.jar
- economyinc-1.6.9.jar

Steps to reproduce:

1. Create new game in creative
2. Open Creative Tab and select transportation register (where the ender chest and tank are)
3. Game crashes

[lastest.log](https://pastebin.com/aeEW9xQv)

[crash.txt](https://pastebin.com/gRVukPDn)

I open the same ticket on the other mod page:
https://github.com/FifouBE/EconomyInc/issues/27

Thank you for your help

**Comment by realTIMematrix** [comment]
#https://github.com/FifouBE/EconomyInc/issues/27

**Comment by covers1624** [comment]
Entities can be constructed with a Null world for rendering purposes, not my bug.

**Comment by realTIMematrix** [comment]
Thank you for checking
