### ISSUE TITLE
Suggestion: Using Emerald and gold as upgrade possibilities

### ISSUE THREAD

**Issue by Thunder-Nova** [TheCBProject/EnderStorage#128]
Since diamond is use to player lock, then how about emerald for capacity (only after player lock) and gold to have a sort of connection access lock.

**For gold**, the main idea is mainly like most other mods that can manipulate connections to pipes and such. It could be used to prevent any form of pipes to be connected. This should work not only as a protection (such from other players that connects their pipes to steal), but also to work with certain pipes that has no way to disconnect (most mods do have ways to disconnect).

**As for Emerald**, simply a personal Capacity upgrade, it shouldn't work for a non-locked ender chest. It cannot be removed once added, even if the lock is removed. It will still be upgraded to the original color that the player used on. _Ex: Green Green Red upgraded to Thunder_Nova, will always be upgraded to all chests of the same color to Thunder_Nova_

In terms for the emerald can only be used once per player color codes. And capacity for tanks, should be in the config, could be useful in certain modpacks. But for chest, should only be no more then double (just to make similar idea to double chests).

**Comment by Ecu** [comment]
No.

**Comment by covers1624** [comment]
As @Ecu said.
Use for gold, is impossible in minecraft without having a completely custom interaction system, so flat out no. Second, also a no, I can perhaps see an addon mod in the future adding 'IronChestEnderChests' style stuff, but no not happening. Thanks for the ideas though, something to think about on the back burner.

**Comment by Morpheus1101** [comment]
The tank is essentially unlimited in the amount they hold, so long as you hook up a pump to an endertank, then by all rights until the source of the fluid at the pump is gone, you can keep draining from the Endertank.  Your idea imho just seems pointless.

**Comment by Thunder-Nova** [comment]
no problem, it was something I had in mind. Mainly for piping "anti-connection", and storage. Perhaps we might see an 'IronChestEnderChests' addon. But who knows.
