### ISSUE TITLE
[1.10.2] Ender Chest/Tank not working after reloading the game

### ISSUE THREAD

**Issue by Greg9711** [TheCBProject/EnderStorage#13]
When i reload the game i have to break and replace my ender chests and ender tank so the work again across dimensions ,but i´m not sure if they work in the same dimension after relogging.

**Comment by TenserD** [comment]
Same prob over here on 1.10.2.

**Comment by Robijnvogel** [comment]
Can confirm.
It seems like ender chests (I have not tested the tanks) become unsynched and start to act like normal chests after the game is reloaded.
Ender pouches, however, work fine.

**Comment by MentalMouse** [comment]
See also https://github.com/TheCBProject/EnderStorage/issues/6 .

**Comment by Robijnvogel** [comment]
I have found that adding "reloadStorage();" on [this line](https://github.com/TheCBProject/EnderStorage/blob/master/src/main/java/codechicken/enderstorage/tile/TileFrequencyOwner.java#L58), seems to fix this issue, at least when playing single player, but God knows what other issues it will cause. Also, it's weird that this hasn't been needed on older Minecraft versions.

**Comment by covers1624** [comment]
This update was a partial rewrite of stuff, I'll check out your investigation.

**Comment by covers1624** [comment]
This is really odd, im unable to reproduce this with placing ender chests in the nether and overworld and they sync as normal after restart, can you provide some instructions to reprduce this please.

**Comment by Robijnvogel** [comment]
They do contain the right materials after restart, however they don't seem to be coupled to their Ender Storage anymore.
This means that you can dupe items.
If you place several Ender chests and put say, a diamond in them and then close and reopen the world, you can take the diamond from all chests (and after this, if you place a new Ender Chest (one that will actually connect to its Ender Storage), you'll see that the Ender Storage still contains that one diamond.

**Comment by Greg9711** [comment]
Steps to reproduce:
1.Place 1 ender chest in the overworld and another one in another dimesion
2.Place like a hopper ontop the ender chest in the overworld and feed items into the ender chest
3.Place a hopper under the ender chest in the other dimension to pull out the items
4.Now the hoppers constantly put in and pull out the items in the ender chest
5.Close Minecraft and reload it
6.Now the hopper in the overworld should still put items in the ender chest but they aren´t getting pulled out because the ender chest in the other dimension isn´t linked anymore until you break and replace the ender chest in the overworld, breaking and replacing the ender chest in the other dimesion didn´t work for me

**Comment by MentalMouse** [comment]
I confirm item duping, and you don't even need other dimensions if you save and reload.

**Comment by Greg9711** [comment]
Ok, i didn´t test it in the overworld

**Comment by covers1624** [comment]
I am still unable to reproduce this in dev, weird..

**Comment by Robijnvogel** [comment]
Can you reproduce this outside of dev?
Overworld and Nether is not needed.
Just 
1. placing an Ender Chest and getting a coupled Ender Pouch
2. exiting to main menu
3. re-entering the game
4. opening the Ender Pouch
You should observe that the Ender Chest does not open. (and is in all ways disconnected from its "Ender Storage").

**Comment by thiakil** [comment]
I have noticed on my install (currently EnderStorage-1.10.2-2.1.3.76) that it happens when one or more of the colours is **white** - chests that have 3 non-white colours seemed to survive the restart. Green/White/White did not.

I also had issues initially that enderpouch of white/white/white did not sync with chests of white/white/white and would not pair with shift clicking. Have not retested this in newer versions though.
