### ISSUE TITLE
[Bug] Quartz converting into diamonds

### ISSUE THREAD

**Issue by takigosciu** [TheCBProject/EnderStorage#132]
The gif should have it all explained, 
Not sure if that is a planned thing, it can be easily repeated (even without the opening chest part)
version: EnderStorage-1.15.2-2.5.0.143-universal
![diamond bug](https://user-images.githubusercontent.com/68331688/87544106-2bcdcd80-c6a6-11ea-9e3d-667b5fb5b1bd.gif)

**Comment by covers1624** [comment]
This issue has been resolved in https://github.com/TheCBProject/EnderStorage/commit/f63cb3e94b9d06368092a6d643db0e3eaee8d775
