### ISSUE TITLE
[BUG] Disconnecting other players from server when placing/opening ender chests

### ISSUE THREAD

**Issue by FripCS** [TheCBProject/EnderStorage#134]
There is a problem with ender chests from Enderstorage mod in skyfactory 4 - disconnects everyone from the server except the host when opening/placing ender chests. Is there a way to fix this?

**Comment by covers1624** [comment]
You will need to provide some Client and Server logs in order to help resolve this issue.

**Comment by covers1624** [comment]
No logs were provided.
