### ISSUE TITLE
ChickenBones links page results in 404

### ISSUE THREAD

**Issue by vedrit** [TheCBProject/EnderStorage#135]
Attempts to visit http://chickenbones.net/Pages/links.html results in a 404
Also tried /pages/links.html (lowercase P in pages)

**Comment by covers1624** [comment]
Correct, the links page is no longer a thing, Mods are available on CurseForge: http://minecraft.curseforge.com/projects/ender-storage-1-8

**Comment by vedrit** [comment]
Both CurseForge and this repository direct users to that link for unstable builds

**Comment by covers1624** [comment]
Should probably update those then.
