### ISSUE TITLE
[Request] Low-Performance Settings

### ISSUE THREAD

**Issue by OutcastOrange** [TheCBProject/EnderStorage#136]
The EnderStorage mod can cause a performance hit, due to the complexity of the model.
In spectator mode, I confirmed that the spinning 'orb' within each chest is ALWAYS rendered and animated, even when the chests are closed. The simulated star-field effect is also rendered while the chests are closed.

I would implore the mod authors to create a low-performance setting within the config, which removes the effects and animations.
Please let Rosethorns know that the models look very nice.

**Comment by OutcastOrange** [comment]
Here I include an image of my pie chart, showing that the mod accounts for roughly 70% of all block entities, which is 26% of total resource use. Scroll down to see the area of my base which is associated with the pie chart. Hopefully it's apparent that I'm using your mod responsibly.

https://imgur.com/a/fxn1opO

The EnderStorage mod is something I really use a lot. I'd be so grateful if anyone could help me find a solution.

**Comment by covers1624** [comment]
Alright,
- Clone the repo, or download the zip of the [1.12.x branch](https://github.com/TheCBProject/EnderStorage/tree/1.12.x).
- Install the Java8 JDK
- You can use `//` to comment lines
- Comment this line: https://github.com/TheCBProject/EnderStorage/blob/1.12.x/src/main/java/codechicken/enderstorage/client/render/tile/RenderTileEnderChest.java#L43
- Comment all of these: https://github.com/TheCBProject/EnderStorage/blob/1.12.x/src/main/java/codechicken/enderstorage/client/render/tile/RenderTileEnderChest.java#L64-L74
- In the root of the project, open cmd/PowerShell/terminal and run `./gradlew build`
- Jar should be in `build/libs/`
If you have any questions, please ask on [discord](http://discord.gg/9nr3qyC).

**Comment by OutcastOrange** [comment]
Thank you very much! I'm seeing a noticeable bump in my performance, thanks to these changes.
I'm happy to see that there are such great mods around, despite the modded Minecraft community being somewhat frustrating to interact with. You guys are a lifesaver!
