### ISSUE TITLE
Chicken Bone Link Broken and How to find links to unstable build/1.16.1 release requirements

### ISSUE THREAD

**Issue by Werner1201** [TheCBProject/EnderStorage#139]
I just want to warn that the link you guys leave in teh curse forge website is broken, [this one](http://chickenbones.net/Pages/links.html). And I'd like to ask what are the requirements to install the EnderStorage-1.16.1-2.6.0.152-universal on my modpack, do I need a core mod or enderstorage is standalone ?

**Comment by covers1624** [comment]
Yes the old website is broken and i haven't gotten around to updating all references to it. EnderStorage for 1.16 has not been released yet, you are on your own in terms of dependencies.
