### ISSUE TITLE
Other players can un-link you from your chests

### ISSUE THREAD

**Issue by sekwah41** [TheCBProject/EnderStorage#140]
Other users are able to take the diamond and unlink the chest.

Was asked to report this after finding it by a friend :)

**Comment by covers1624** [comment]
Not sure if this is something we are gonna fix @Ecu, Thoughts?

**Comment by covers1624** [comment]
This is intended. Diamonds only give you a separate frequency band, not security.

**Comment by sekwah41** [comment]
Ah alright, the member was thinking it was a bug and asked me to report it.
