### ISSUE TITLE
EnderStorage crash 1.16.3

### ISSUE THREAD

**Issue by omeranha** [TheCBProject/EnderStorage#141]
java.lang.RuntimeException: java.io.IOException: The system cannot find the path specified
    at codechicken.enderstorage.manager.EnderStorageManager.save(EnderStorageManager.java:179)

here is the log file:
[latest.log](https://github.com/TheCBProject/EnderStorage/files/5534086/latest.log)

EnderStorage 1.16.3-2.7.0.156
CodeChickenLib-1.16.3-3.5.0.392-universal
Forge 34.1.42

**Comment by covers1624** [comment]
From your log, many other files failed to save aswell, make sure your not on a OneDrive and have some free space available on your C drive
