### ISSUE TITLE
[question] recipe ids

### ISSUE THREAD

**Issue by xemnes** [TheCBProject/EnderStorage#143]
hi, i was wondering how to find the recipe ids for the blocks of this mod as jei doesnt seem to show them.
im creating a very large manual for my modpack using patchouli, one of the features is to show crafting recipes in the book which requires a recipe id to show it.
i tried using their item ids such as enderstorage:ender_storage but sadly that didnt work.

**Comment by covers1624** [comment]
Provided you haven't removed or changed the recipes, you can see their registration names [here](https://github.com/TheCBProject/EnderStorage/tree/1.12.x/src/main/resources/assets/enderstorage/recipes).

**Comment by xemnes** [comment]
hmm they dont seem to work for some reason, patchouli still renders a blank page.
i think i will just resort to a custom template for now since this doesnt seem possible.
