### ISSUE TITLE
Linking a chest with a diamond links by username, not UUID

### ISSUE THREAD

**Issue by BLucky-gh** [TheCBProject/EnderStorage#144]
I got my acc hacked and my username changed, so for the next 30 days I won't be able to change my username back, and I can't make new chests that link to my old chests because they link with my new username, and the old chests still show my old username. This makes expansion really annoying because I'm just used to plopping down a chest and right clicking it with a diamond.

**Comment by covers1624** [comment]
1.12 is not supported anymore, unfortunately. This has also been resolved in 1.15+.

**Comment by BLucky-gh** [comment]
OK, thanks for the quick reply anyways
