### ISSUE TITLE
Endertank gltich?

### ISSUE THREAD

**Issue by PossesiveGamer** [TheCBProject/EnderStorage#145]
So im playing with EnderStorage-1.16.4-2.7.0.159-universal and I crafted an endertank for a lava farm. Well when I placed the ender tank down it was showing me the spawner and chests next to my house along with a few things way underground. Here is a video showing what is happening. I dont quite know how to explain it. Hope I did my best lol.

Video was too big so had to upload somewhere else. Its a quick 23 second video showing it.
https://streamable.com/9frhmp

Also placing the ender tank on top of a builder in the nether did this...
![2020-12-27_23 07 24](https://user-images.githubusercontent.com/9295473/103190884-6a43f700-4898-11eb-8757-d96d6ecd82c3.png)

**Comment by Ordenkeim93499** [comment]
Can confirm this glitch. I'ts also happening to me.
Maybe the newer 1.16.4-2.7.0.161.jar is fixing this problem. 
I'll get back later if it fixed this glitch. :)
[EDIT]: So I tried the new files (CodeChickenLib-1.16.4-3.5.0.401-universal & EnderStorage-1.16.4-2.7.0.161-universal) but unfortunately it didn't help. The Glitch still persists. :(

**Comment by Quadae** [comment]
Also having a similar issue, whenever the endertank is in view, all tile entities appear through walls

**Comment by xElementzx** [comment]
I have been unable to reproduce this issue, do you have Optifine installed?
Can I also have a client log if possible?

**Comment by Ordenkeim93499** [comment]
Allright so I tested it without Optifine and @xElementzx was right. Optifine was indeed the culprit.
Maybe using a different version of Optifine and Optiforge will fix it.
I'am going to try out different versions and post my results here if it's OK. :)
Issue could probably be closed.

But what makes me wonder is why in older version the tanks and chests always worked fine even with Optifine installed. 
Hmm weird...

**Comment by PossesiveGamer** [comment]
That is fine to test it out @Ordenkeim93499 I have stopped playing 1.16.4 currently so till more come out and things are more stable. And it could be the new rendering layout. I believe Microsoft changed all that in the new versions. Optifine changes a lot of things behind the scenes and likes to conflict with a lot of mods. That’s why authors ask for it in cases like this cause it’s usually an Optifine issue and not theirs.
