### ISSUE TITLE
enderstorage

### ISSUE THREAD

**Issue by epiczero2** [TheCBProject/EnderStorage#146]
the mod had been causing crashes on the mod pack ftb i have not been able to play for hours and waiting for the problem to be fixed.

**Comment by covers1624** [comment]
I can't help you without a crash report. Please provide a crash report.

**Comment by epiczero2** [comment]
crash 2021-10-14 02.13.13-sever txt it will not let me get a proper link but there is the information it gives. with every crash i have tried to get a crash report and every time it tells me fails.

**Comment by epiczero2** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/76937693/103514838-19517700-4e33-11eb-9e8e-97cb0bf8a34d.png)
here is a screen shot of the crash

**Comment by covers1624** [comment]
You should be able to click on the bright green link to open the crash report file locally, then you can upload it somewhere manually. As it sits, there is no useful information here to debug things.

**Comment by xElementzx** [comment]
No Response from the author in 7 days, if this issue still persists please open another issue with your crash report included.
