### ISSUE TITLE
Config to disable placing ender pouch inside ender pouch

### ISSUE THREAD

**Issue by zachsai** [TheCBProject/EnderStorage#148]
Hi,
the title speaks for itself, would it be possible to add a config to disable the ability to place ender pouches inside ender pouches (To encourage player to use shulker boxes)

**Comment by covers1624** [comment]
Creating 2 of the same color ender chest does not give you more storage. Go ahead and place them inside each other all you want.
This is intended, and not a balance point I am interested in.
