### ISSUE TITLE
Crash when used with Create

### ISSUE THREAD

**Issue by Sunekaer** [TheCBProject/EnderStorage#149]
Issue: Game crashes when using a schematic cannon to place an ender tank
Link: https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5826690/crash-2021-01-17_14.46.45-server.txt

CodeChickenLib-1.16.4-3.5.0.401-universal.jar
create-mc1.16.3_v0.3e.jar
EnderStorage-1.16.4-2.7.0.161-universal.jar

**Comment by covers1624** [comment]
Should be fixed with https://maven.covers1624.net/codechicken/CodeChickenLib/1.16.4-3.5.1.408/CodeChickenLib-1.16.4-3.5.1.408-universal.jar and https://maven.covers1624.net/codechicken/EnderStorage/1.16.4-2.7.1.166/EnderStorage-1.16.4-2.7.1.166-universal.jar
