### ISSUE TITLE
inventory and other GUIs (I tried chest, golden bag, bagginses bag, mekanism, ender i/o) are partially transparent

### ISSUE THREAD

**Issue by croftyraider** [TheCBProject/EnderStorage#15]
3rd times the charm I hope... After talking with mezz of JEI, he's pointing the finger at your mod, so here's the data:

I had added your mod to my version of the FTB Unstable modpack and one day I noticed that my inventory GUI was transparent. When I saw that I also looked at a mekanism energy cube, an Ender IO machine, and so on, and they were all messed up.

My search term in JEI was "@stor" which was showing stuff from your EnderStorage mod, plus Storage Drawers plus Refined Storage. After discussing with mezz, and giving him a repeatable test case he said this:

> Thanks for narrowing it down.
> I did some testing: if I hide EnderStorage's Ender Chest and Ender Tank from the item list, the problem goes away. You can further confirm this by having those items in your inventory; it messes with the lighting of other regular items in the inventory.

To repeat the issue, use MultiMC with minecraft 1.10.2 then install forge 2075. After that, add these mods:

Chameleon-1.9.4-2.1.6.jar*
CodeChickenCore-1.10.2-2.1.8.79-universal.jar*
EnderStorage-1.10.2-2.1.3.73-universal.jar*
jei_1.10.2-3.9.0.244.jar*
journeymap-1.10.2-5.2.4-unlimited.jar*
JustEnoughResources-1.10.2-0.4.6.41.jar*
refinedstorage-0.8.10.jar*
StorageDrawers-1.9.4-3.2.0.jar*
Waila-1.7.0-B3_1.9.4.jar*
WailaHarvestability-mc1.10-1.1.7.jar*
Wawla-1.10-2.3.0.193.jar*

Create a new world then put in @stor in your search term in JEI and don't forget to switch to a survival mode (creative inventory doesn't show the issue for some reason).

Thanks!

**Comment by covers1624** [comment]
Try the lastest version off http://chickenbones.net/Pages/links.html

**Comment by croftyraider** [comment]
Updated to EnderStorage-1.10.2-2.1.3.75-universal.jar and it did exactly the same thing.

I also tried putting in an ender pouch and an ender chest into my hotbar, then switching to survival. Going into my inventory I can see that the place where items go into the right hand is drawn wrong.

**Comment by covers1624** [comment]
can you verify that it is only stacked items causing this issue?

**Comment by croftyraider** [comment]
No? Not sure what you mean by that - can ender pouches/ender chests be 
stacked?

**Comment by covers1624** [comment]
So, a stack of more than one EnderTank in the inventory.

**Comment by croftyraider** [comment]
Here are screenshots showing the various errors I found
![2016-09-17_09 16 42](https://cloud.githubusercontent.com/assets/7588838/18609509/a2cc50dc-7cb8-11e6-9fd2-c80dbe9a31a7.png)
![2016-09-17_09 17 13](https://cloud.githubusercontent.com/assets/7588838/18609511/a2cf1f24-7cb8-11e6-83e2-3c3c23e4e3bb.png)
![2016-09-17_09 17 40](https://cloud.githubusercontent.com/assets/7588838/18609510/a2ce44be-7cb8-11e6-9e75-7300d38ae7dd.png)
![2016-09-17_09 18 57](https://cloud.githubusercontent.com/assets/7588838/18609507/a2c9b138-7cb8-11e6-913c-0bc4473ffb5a.png)
![2016-09-17_09 19 16](https://cloud.githubusercontent.com/assets/7588838/18609508/a2cade00-7cb8-11e6-9c2d-e38451cea0b7.png)

**Comment by croftyraider** [comment]
Note that the endertanks render wrong until you put one down in the world. Then they are fine. Any questions about the screenshots, just ask.

**Comment by gigabit101** [comment]
this issue is already known and is being worked on

**Comment by covers1624** [comment]
Are the GUI artifacts only an issue if there is more than 1 ender tank in the stack?
and is it only the ender tank that causes this or the ender chest as well.

**Comment by covers1624** [comment]
Please confirm this is still an issue on latest build.

**Comment by croftyraider** [comment]
Still broken on ender storage .77 and code chicken core .80

**Comment by stor** [comment]
Hello,

Why am I getting these emails? What is this?

Regards,

Stein O. R.

2016-10-10 13:08 GMT+02:00 covers1624 notifications@github.com:

**Comment by covers1624** [comment]
I closed the issue, and you are probably watching the repo.
