### ISSUE TITLE
[Feature Request] Config option to disable special rendering

### ISSUE THREAD

**Issue by Dakedres** [TheCBProject/EnderStorage#150]
It would be nice if there were a config option to disable the super-cool-and-rad opening animation when using super-not-cool (and otherwise incompatible) rendering mods like Optifine, which are sometimes necessary on lower-end machines, especially in modern versions, which lack many friendlier optimization mods.

Thanks!

**Comment by covers1624** [comment]
This will not be happening.
I am not adding workarounds for other mods, the EnderChest renders as a standard chest, and the other model parts are standard OBJ models that have worked and rendered fine with Optifine for literal years.

I will consider adding a config to turn off the starfield, but it is super low priority.

**Comment by Dakedres** [comment]
Yes, I was referring to the starfield. Sorry, should've been a bit clearer.
