### ISSUE TITLE
Opening Ender Pouch causes tile entities to be seen through walls

### ISSUE THREAD

**Issue by Lumosium** [TheCBProject/EnderStorage#153]
Im playing the Valhelsia 3 (3.1.7) with optiforge (1.16.5-0.5.0) and optifine (1.16.5_HD_U_G6). EnderStorage (1.16.4-2.7.0.161-universal) comes with the pack, upon using my ender pouch I noticed that the UI that pops up causes all tile entities to render through walls. I've attached the before and after photos:
![2021-02-21_12 58 25](https://user-images.githubusercontent.com/79422655/108638678-3672f100-7445-11eb-94c3-0ad857978814.png)
![2021-02-21_12 58 28](https://user-images.githubusercontent.com/79422655/108638681-3a067800-7445-11eb-8755-e63b067d2bb6.png)

This is my first bug report so please let me know if you need anything more. Thanks so much for this amazing mod that's made my storage systems so easy since 1.4

**Comment by covers1624** [comment]
This is a bug with optifine, disable its Fast Renderer option or remove it.
