### ISSUE TITLE
Enderstorage and revealing itself through walls?

### ISSUE THREAD

**Issue by skytheraiders** [TheCBProject/EnderStorage#154]
This is honestly a tough thing to explain but, when I put down an ender tank or I interact with the ender chest from the mod, textures "pop" in relative to their positions in the world. I'll add a video to try and explain it better but it only happens when I put down the Ender tank or I open the ender chest. 

Video: https://youtu.be/sraWiavlPzo

**Comment by skytheraiders** [comment]
I also tried using older versions but they all have the same issue

**Comment by skytheraiders** [comment]
After doing much needed testing, it turns out to be an issue with Fast Render with Optifine

**Comment by xElementzx** [comment]
Using Optifine is going to cause rendering issues that aren't easily fixable, turn off fast render for less issues.
Optifine is not supported.
