### ISSUE TITLE
Tag 1.16 in curse?

### ISSUE THREAD

**Issue by YTMrSnipa** [TheCBProject/EnderStorage#155]
Hey! Can you fix the "Game Version" Please?
I can't add them to me modpack via the curseforge app cos this mod is in older verions!

Thanks!
![image](https://user-images.githubusercontent.com/67626963/109203202-de801580-77c9-11eb-9671-6aefcecd22cb.png)

**Comment by covers1624** [comment]
Done, marked as 1.16.4&1.16.5.

Once an official RB for forge gets released for 1.16.5, 1.16.4 support will be dropped.
