### ISSUE TITLE
Open ender pouch using a button shorcut

### ISSUE THREAD

**Issue by the-vindex** [TheCBProject/EnderStorage#156]
Please consider a functionality to open ender pouch using button shortcut instead of having it in hotbar.

Probably the most straightforward way is how Backpacks mod does it:
- Shift + shortcut key - enables you to "equip" the backpack (open UI with a single slot)
- Shortcut key opens it

Thanks.

**Comment by covers1624** [comment]
Not interested in this feature. Ender Storage is meant to be simple and compliment vanilla.
