### ISSUE TITLE
Can't private chest in 1.16.5

### ISSUE THREAD

**Issue by TaeoG** [TheCBProject/EnderStorage#158]
I'm using EnderStorage 1.16.4-2.7.1.166 on forge 1.16.5-36.0.40, and I cannot seem to get the private chest to work. The config is the default, requiring a diamond, but nothing happens when I try. Left click or right click, shift or not. Right clicking opens the inventory. Am I doing it wrong?

**Comment by covers1624** [comment]
You are right-clicking the latch correct?

**Comment by TaeoG** [comment]
I am, yes, I tried a bunch of other types of clicking when that didn't work, but that was the first thing

**Comment by TaeoG** [comment]
I tried it from all angles as well. The little hitbox appears around the latch but right clicking just opens it

**Comment by TheRealWormbo** [comment]
I can confirm that using a diamond on the latch actually works on Minecraft 1.16.5, using EnderStorage 2.7.1.166 on Forge 36.1.0.
