### ISSUE TITLE
[1.10.2] Compatibility crash with BloodMagic (Altar)

### ISSUE THREAD

**Issue by Robijnvogel** [TheCBProject/EnderStorage#16]
See https://github.com/WayofTime/BloodMagic/issues/928

**Comment by covers1624** [comment]
Check latest build, What change did you make may i ask?

**Comment by Robijnvogel** [comment]
Just that thing I proposed in issue #13
https://github.com/TheCBProject/EnderStorage/issues/13#issuecomment-244606228

**Comment by covers1624** [comment]
This is soo old and is most likely fixed, BloodMagic and ES are in modpacks together now.
