### ISSUE TITLE
Shulker Storage

### ISSUE THREAD

**Issue by lostallmymoney** [TheCBProject/EnderStorage#162]
Ok hear me out, 1st, change for fabric for snapshot support.
2nd : SHULKER STORAGE ..
3rd : Make it vanilla client compatible !!
4th : Rename an ender perl and craft it together with a shulker box to get a channel on your shulker, The storage channel will be the 64 or 128 first characters of the ender pearl's name, allowing servers to have a massive amount of channels.

ENDER STORAGE NOW IN VANILLA !!

Idk shit about coding a fabric mod so if someone is as eager as me for the Shulker Storage please please PLEASE
Also I can code but I don't know anything about fabric so if someone's got a lead so I can smooth into it..
Also if someone does it my version is 21w14a :) :) :)
I hope I'm reaching out the right place :)

**Comment by lostallmymoney** [comment]
Also give enchant the shulker box for hype

**Comment by covers1624** [comment]
I will not be supporting fabric.
