### ISSUE TITLE
[CRASH][1.16.5] Ender Tank crashes the game when rendered with iskall85s vault mod.

### ISSUE THREAD

**Issue by JoeFoxe** [TheCBProject/EnderStorage#164]
https://gist.github.com/JoeFoxe/b532b6646fb7290842828c299963f088

Im pretty new to modpack development and I would really appreciate some help, im not sure where to turn but i saw a similar bug on a previous issue but im not sure how I only get this issue with the vault mod installed. I tested this as well with only the vault jei and ender storage and got the same error. I really have no idea what I can do to try to fix this, any help or pointing of the right direction would be much appreciated :)

**Comment by covers1624** [comment]
`iskallia.vault.event.EntityEvents.onEntityTick3` Report this to the mod author of this mod. Entities can have null worlds for rendering purposes.
