### ISSUE TITLE
Other players can access my diamond EnderStorage Network

### ISSUE THREAD

**Issue by ghost** [TheCBProject/EnderStorage#166]
Title says it all
Steps to recreate:
Place an EnderStorage Ender Chest
Colour code
Diamond the latch (making it my unique network)
Have another player see if they can see my items

**Comment by covers1624** [comment]
This is intended behavior. They are Personal, not Private.

Duplicate of https://github.com/TheCBProject/EnderStorage/issues/85

**Comment by ghost** [comment]
Then what's the point? What does making it personal do?

**Comment by covers1624** [comment]
It gives you your own Personal frequency range. It does not lock the chest/tank from being accessible by other players otherwise Automation could not access it also.
