### ISSUE TITLE
[Suggestion] In-game guide for the endertank

### ISSUE THREAD

**Issue by Ch1216** [TheCBProject/EnderStorage#167]
A guide for what the ender tank's gold valve with red and blue symbols does, or just mention it anywhere, I have no idea what it does

**Comment by covers1624** [comment]
This will be provided via Project Intelligence and is on my todo list.

**Comment by Ch1216** [comment]
ok, also can you tell what it does currently, or will I have to wait

**Comment by covers1624** [comment]
Orange: Auto-eject (output)
Blue: Nothing (input)

These are the community standard colors for input/output.
