### ISSUE TITLE
spawner icon

### ISSUE THREAD

**Issue by TameEnderman923** [TheCBProject/EnderStorage#168]
when you open an ender chest or place down an ender tank they show the mob icon in the spawn through walls

**Comment by covers1624** [comment]
I have absolutely no idea what you are trying to convey. Provide a screenshot.

**Comment by TameEnderman923** [comment]
![2021-08-05_02 24 58](https://user-images.githubusercontent.com/52027516/128309149-3fb6995e-3eaf-454b-8777-51f77d37f89e.png)

**Comment by covers1624** [comment]
Do you have Optifine installed?

**Comment by TameEnderman923** [comment]
yes

**Comment by covers1624** [comment]
Optifine is not supported. Disable Optifine fast render or remove optifine.
