### ISSUE TITLE
Repetitive crashing 

### ISSUE THREAD

**Issue by ghost** [TheCBProject/EnderStorage#169]
The enderchest keeps saying crashing my game despite not using that mod in my world. It is worth mentioning that I have optifine installed.
[crash-2021-09-13_19.14.22-client.txt](https://github.com/TheCBProject/EnderStorage/files/7158441/crash-2021-09-13_19.14.22-client.txt)

**Comment by covers1624** [comment]
You have an incredibly outdated version of EnderSotrage for 1.16.4 installed, dispite running Minecraft 1.16.5.
