### ISSUE TITLE
Ender Chests and Bags Losing Sync

### ISSUE THREAD

**Issue by helmutfork** [TheCBProject/EnderStorage#17]
Ender chests and pouches setup with the same color scheme lose sync when server is restarted.  Chests have to be broken and re-placed in order to sync with pouch again.  Have confirmed that this also happens in single player world after logging out and logging back in.  There are no apparent errors in log.

Forge version: 12.18.1.2095
Ender Storage: 1.10.2-2.1.3.72
Currently running GabelCraft modpack v1.5.0 (https://minecraft.curseforge.com/projects/gabelcraft)

How to replicate:
Create ender chest and ender pouch using the same color scheme (brown brown brown in my situation).  Restart server and log back in (multiplayer), or log out and log back in (single player).  Place item in pouch, and verify that item does not appear in chest (also chest does not appear to open in background when opening pouch).  Break chest, and then place again.  Now item placed in pouch now appears in chest as well.

**Comment by gigabit101** [comment]
This has been fixed in newer builds update

**Comment by Shininji** [comment]
Sorry to say but this issue is not fixed at all, still getting it with the present version, wich is the one helmutfork used, unless the next one is planned to be released shortly given the fact it has been almost 2 months without updates

Thanks for the mod and keep up the good work anyway!!

**Comment by gigabit101** [comment]
http://chickenbones.net/Pages/links.html

**Comment by gigabit101** [comment]
get newer builds there

**Comment by Shininji** [comment]
Thank you! My bad for not investigating hard enough!!

**Comment by covers1624** [comment]
Im working on fixing the inventory rendering issues, and there is some breaking internal changes coming in CCL so when they are done a new build will be pushed to curse.

**Comment by MentalMouse** [comment]
Still Present in EnderStorage-1.10.2-2.1.3.76-universal.jar.  I see there is a .77 version at chickenbones.net, I will try that.

ETA:  OK, the .77 version seems to have fixed it.
