### ISSUE TITLE
Ender Tanks Tanks PLS HELPPP

### ISSUE THREAD

**Issue by ItsChase7** [TheCBProject/EnderStorage#172]
When playing skyfactory one, when i put down the ender tanks they started making my screen glitch as shown in the picture, anyone know how to fix this?
![2021-10-24_12 31 43](https://user-images.githubusercontent.com/84806565/138603589-8a8e856f-8720-4e1b-a803-0262177ab80d.png)

**Comment by covers1624** [comment]
Remove optifine or disable Optifine FastRenderer.

In the future please look at the previous closed issues before creating a new one.
