### ISSUE TITLE
Ender Tank and Chest corrupts textures when placed

### ISSUE THREAD

**Issue by LolJohn11** [TheCBProject/EnderStorage#173]
Ender tank is messing up other textures when placed: signs become visible through solid blocks, shulkers become turned inside-out, etc.
Screenshots:
![2021-10-25_19 26 22](https://user-images.githubusercontent.com/49366383/138734373-9d91b01a-9dac-4938-bbf3-e6b8d1b43958.png)
![2021-10-25_19 26 24](https://user-images.githubusercontent.com/49366383/138734381-b7677233-ba07-4c27-8264-dd3ae905655e.png)

The same issue happens when the animation of the ender chest opening is playing.

Mods installed:
https://pastebin.com/9kUyA4KJ

**Comment by ItsChase7** [comment]
I am having the same issue, please tell me if you find a solution

**Comment by covers1624** [comment]
Remove Optifine., or disable Optifine Fast renderer.

Please look at the previous closed issues before posting a new one.

Duplicate of: https://github.com/TheCBProject/EnderStorage/issues/172
