### ISSUE TITLE
[1.16.5 - v2.8.0.168] Rendering Crash

### ISSUE THREAD

**Issue by Elfinlocks** [TheCBProject/EnderStorage#178]
When attempting to view the Ender Tank from this mod, the game crashes. I have only been able to avoid this by **downgrading** the following mods (seemingly unrelated?) to the following versions from their release version:

Tinker's Construct build 271
Mantle v.127
Tinker's Construct Planner v1.1.0

I am unsure where such an interaction is occurring, but please see below for crash log and Crashy link:

[crash-2021-12-27_09.11.43-client.txt](https://github.com/TheCBProject/EnderStorage/files/7781425/crash-2021-12-27_09.11.43-client.txt)

https://crashy.net/vkFnV7sOeVhAC79ICdnv

Lastly, this was performed by attempting to update the previously listed mods to their latest versions in my modpack, Astral Engineering. You may download the pack to get an easy testing environment at this link:

https://www.curseforge.com/minecraft/modpacks/astral-engineering/files/3578307

Thanks!

**Comment by covers1624** [comment]
The crash report does not appear to be related to EnderStorage in any way.

Please update CCL, the version you are using is at least 5 versions out-of-date and see if your issue persists.

If your issue persists i recommend reporting this to the tardis mod.
