### ISSUE TITLE
Suggestion ; Vanilla Ender Storage (nbt ender shulkers)

### ISSUE THREAD

**Issue by lostallmymoney** [TheCBProject/EnderStorage#179]
Hi, I'm suggesting this mod could be repurposed for a vanilla mod where you have shulkers you can change the frequency with a command or wool in the crafting table.
I think it wouldn't be too much work except that you'd need to mixin in the shulker boxes to make it work with enderstorage but this could be a viable vanilla+ alternative that a lot of vanilla players would like to play. EShulks would behave just like EStorage chests but the appeal of vanilla E shulkers would be big as this is a feature some players would like to see implemented in the game.
Some vanilla+ server would approve

**Comment by lostallmymoney** [comment]
Maybe rename an enderpearl and craft it with a shulker to get e shulker on the renamed frequency to prevent people accessing other's shulkers too easily (adds more frequencies).

**Comment by Ecu** [comment]
No.

I don't see how this would benefit the mod at all.  Shulker Chests provide a different purpose when compared to Ender Storage.

**Comment by covers1624** [comment]
This won't be happening. Sorry.
