### ISSUE TITLE
[1.16.5 - 2.8.0.168] Ender Chest rendering crash

### ISSUE THREAD

**Issue by Nigi1** [TheCBProject/EnderStorage#181]
When I try to view the Ender Chest in JEI or in the creative menu the game instantly crashes. I've tried downgrading several versions from EnderChest and CodeChickenLib but nothing seemed to work. I had a look at the stacktrace but I wasn't able to find the problem. I also had a look at past issues and didn't find something that matched my problem. Because of that I think it might interfere with another mod which causes it to crash, but I'm no expert so maybe there is something I am missing.

Here is the crash report:
https://pastebin.com/SFA43TjV

**Comment by covers1624** [comment]
Remove RoadRunner, it is modifying the Minecraft render pipeline in a way that is not compatible with CodeChickenLib/EnderStorage.
