### ISSUE TITLE
[1.18.2] EnderStorage Crashes on Startup

### ISSUE THREAD

**Issue by DoughnutDev** [TheCBProject/EnderStorage#183]
Removing EnderStorage allows the game to launch. This is also only happening on one computer my other one is working just fine with the same exact mods.

Currently running:
EnderStorage: 1.18.2-2.9.0.175
CodeChickenLib: 1.18-4.1.0.458
Forge: 1.18.2-40.1.19

Crashlog:
https://paste.ee/p/FTBSr

**Comment by DoughnutDev** [comment]
Issue resolved. I had the user change from integrated graphics to his NVIDIA graphics and it worked not sure why it was defaulting to the other one.

**Comment by covers1624** [comment]
Glad you solved this. This would have been because of your integrated gpu drivers not properly supporting the OpenGL features required for shaders.
