### ISSUE TITLE
When i open the ender chest after closing it, i cannot see my items anymore

### ISSUE THREAD

**Issue by Sakatsuky** [TheCBProject/EnderStorage#185]
but they're there, i can see them with jade mod

CodeChicken Lib 1.18.2-4.1.0.460-universal
Ender Storage 1.18.2-2.9.0.177-universal

**Comment by ShibeTemple** [comment]
I have the same issue

**Comment by ShibeTemple** [comment]
Items that were put into an ender chest or ender pouch are not rendered again after closing the inventory screen. Causes unexpected item behaviour. Items are visible by Jade and can be pulled by a hopper.

**Comment by Sakatsuky** [comment]
Yes, i also can import the items to refined storage system without problems, apparently it's just the render when opening the chest that is bugged

**Comment by ShibeTemple** [comment]
You can place the ender bag into itself as well. Shift-clicking items into the pouch also causes inventory issues if there are invisible items.

**Comment by walksanatora** [comment]
i am having a similar problem where it appears the ender chest is voiding items
but when i attach a hopper to another ender chest they appear there but not in the chest it's self

**Comment by covers1624** [comment]
This should be resolved by updating to CodeChickenLib [`4.1.0.461`](https://maven.covers1624.net/codechicken/CodeChickenLib/1.18.2-4.1.0.461/CodeChickenLib-1.18.2-4.1.0.461-universal.jar) (pending approval on CurseForge)
