### ISSUE TITLE
EnderStorage encountered an error during the done event phase?

### ISSUE THREAD

**Issue by TheNickofTime22** [TheCBProject/EnderStorage#186]
It's part of a huge modpack so I cant say for sure it's the mod's fault, but disabling the mod allows the whole pack to load and with it, it crashes before the title screen every time.

I cant make too much sense of the crash report  though
[crash-2022-06-04_08.17.10-client.txt](https://github.com/TheCBProject/EnderStorage/files/8837076/crash-2022-06-04_08.17.10-client.txt)

**Comment by Sakatsuky** [comment]
try deleting the EnderStorage.cfg file inside the .minecraft/config folder, sometimes deleting the config file of a mod that presents this error it fix it

**Comment by covers1624** [comment]
Please update to EnderStorage `2.9.0.177`.

This bug has already been resolved.
