### ISSUE TITLE
[issue] crashing when opening chest/storage

### ISSUE THREAD

**Issue by analinux** [TheCBProject/EnderStorage#188]
https://paste.gg/p/anonymous/5ff55968bac64f1091360a0dc90febc6
https://paste.gg/p/anonymous/30a7708c88424e62947a0b14985968b0

Okay this is my first time opening any issue on github. so bare with me if I did something wrong by accident. 
a quick rundown is. player puts down a chest, links to another. opens said chest, and then it crashes.
version is 1.16.5 if i need to provide a full mod list I can
if anyone responds here and i dont reply please contact me directly at discord :) anast9sia#1414
![image](https://user-images.githubusercontent.com/74432523/173920024-89741c8d-fb8c-408d-b795-f9ff01b4c484.png)

**Comment by covers1624** [comment]
Can you please provide your full crash report, there is almost no information here to debug with.

**Comment by analinux** [comment]
> Can you please provide your full crash report, there is almost no information here to debug with.
https://bin.bloom.host/uvubofuvaj here you go sorry, i was having computer problems and could'nt respond

**Comment by covers1624** [comment]
Magma is not supported and will never be supported. They are removing a function that EnderStorage calls.

If you can reproduce this in a pure Forge environment, i may be able to take a look.
