### ISSUE TITLE
Crafting Recipe Modifications Not Working

### ISSUE THREAD

**Issue by LilJagty** [TheCBProject/EnderStorage#189]
Hi, how do you suggest editing the crafting recipes for your items? Using KubeJS, I've been unsuccessful in changing the crafting recipe for anything in the ender storage mod. I'm trying to gate their usage behind the Waystones warp stone, which I've already successfully done with other mods. 
**Script:**
```
    // EnderStorage tweaks

    // Ender tank
    event.replaceInput({id: 'enderstorage:ender_tank'}, 'minecraft:ender_pearl', 'waystones:warp_stone');

    // Ender chest
    event.replaceInput({id: 'enderstorage:ender_chest'}, 'minecraft:ender_pearl', 'waystones:warp_stone');

    // Ender bag
    event.replaceInput({id: 'enderstorage:ender_pouch'}, 'minecraft:ender_pearl', 'waystones:warp_stone');
```
**Expected Result:**
The ender pearl in all three recipes is replaced with the warp stone in all three crafting recipes.

**Actual Result:**
The crafting recipes remained completely unchanged, but KubeJS does not give any error or warning messages that would indicate a broken script.

Versions:
Minecraft 1.18.2
Forge 40.1.41
kubejs-forge-1802.5.4-build.492
EnderStorage-1.18.2-2.9.0.177

**Comment by covers1624** [comment]
The EnderTank/Chest/Pouch uses custom recipes. It is likely that KubeJS does not support these.

You will either need to replace the entire recipe and lose the coloring support (colored wool -> colored chest/tank/pouch, etc), or you will need to use a data pack to adjust the recipes.

If you want to go with a data pack, the recipe jsons are visible in this repository and easily editable how you wish, the Minecraft wiki has some resources on creating data packs. By default vanilla requires that these are added to specific worlds, however, KubeJS may have something to load them, or other may be other mods that can do this.

Good luck :)
