### ISSUE TITLE
Server launch crash after updating to latest version.

### ISSUE THREAD

**Issue by Johnne25** [TheCBProject/EnderStorage#19]
Minecraft 1.10.2

I receive a message in the game saying there is a new version EnderStorage.
I update the mod, when launching I get an error saying I also need to update CodeChickenCore.
After updating those two components I get a server crash when launching.

**Comment by Johnne25** [comment]
[crash-2016-10-14_11.54.22-client.txt](https://github.com/TheCBProject/EnderStorage/files/529947/crash-2016-10-14_11.54.22-client.txt)

**Comment by covers1624** [comment]
Update translocators.

**Comment by Johnne25** [comment]
Awesome it worked!  Thanks a ton for the fast response.
