### ISSUE TITLE
Ender Chest has no preferred tool and takes a very long time to mine

### ISSUE THREAD

**Issue by Nataly171** [TheCBProject/EnderStorage#195]
The Ender Chests in this mod don't have a preferred tool, and as such, using a pickaxe to break them is no faster than a fist, and both options are very slow. Is this intended behavior?

Minecraft Version: 1.18.2
Forge Version: 40.1.60
Ender Storage Version: 2.9.0.177
CodeChicken Lib Version: 4.1.1.462

**Comment by stop-x13** [comment]
Add a mineable tag for the blocks using datapack or open loader or just edit the mod's datapack. Adding "pickaxe.json" containing:
{
  "replace": false,
  "values": [
    "enderstorage:ender_chest",
    "enderstorage:ender_tank"
  ]
} 
in packname/data/minecraft/tags/blocks/mineable, packname can be anything

**Comment by covers1624** [comment]
This has been resolved in both 1.19.2 and 1.18.2
