### ISSUE TITLE
Ender Storage has falied to load correctly

### ISSUE THREAD

**Issue by Dustynzzz** [TheCBProject/EnderStorage#196]
Minecraft Version: 1.19
Forge Version: 41.0.96

Mod error: java.lang.reflect.InvocationTargetExeption: null
[crash-2022-07-16_15.21.45-fml.txt](https://github.com/TheCBProject/EnderStorage/files/9125883/crash-2022-07-16_15.21.45-fml.txt)
[latest.log](https://github.com/TheCBProject/EnderStorage/files/9125884/latest.log)

**Comment by theslimebee** [comment]
I'm having the same issue in Forge 41.0.100



[crash-2022-07-18_12.35.26-fml.txt](https://github.com/TheCBProject/EnderStorage/files/9135321/crash-2022-07-18_12.35.26-fml.txt)


EDIT: I switched from EnderStorage-1.19-2.10.0.179-universal to EnderStorage-1.19-2.10.0.180-universal and the issue miraculously fixed itself

**Comment by covers1624** [comment]
This was resolved a long time ago and was caused by Forge refactors and breaking changes.
