### ISSUE TITLE
Right clicking the latch of ender chest will simply open the chest when holding a diamond

### ISSUE THREAD

**Issue by stop-x13** [TheCBProject/EnderStorage#197]
"Using a diamond on the latch of an Ender Chest will move it to a seperate network for the player that used the diamond" doesn't work at all.

**Comment by szdytom** [comment]
u need to press SHIFT before right clicking :)

**Comment by stop-x13** [comment]
> u need to press SHIFT before right clicking :)

No it didn't work before and it works now maybe because there was mod conflict, no need shift

**Comment by covers1624** [comment]
I am unable to reproduce this issue.

Please double-check the config has not been altered.
