### ISSUE TITLE
Enderstorage corruption - Crashing

### ISSUE THREAD

**Issue by HenrikoMagnifico** [TheCBProject/EnderStorage#198]
[crash-2022-07-22_20.49.48-server.txt](https://github.com/TheCBProject/EnderStorage/files/9212234/crash-2022-07-22_20.49.48-server.txt)

**Comment by MelanX** [comment]
> EnderStorage was unable to read it's data, please delete the 'EnderStorage' folder Here: C:\Users\scott\AppData\Roaming\\.technic\modpacks\yaopack\saves\New World\EnderStorage and start the server again.

**Comment by covers1624** [comment]
As the exerpt from the log says, nuke the folder.
