### ISSUE TITLE
[Feature Request] Upgraded Ender Pouch

### ISSUE THREAD

**Issue by Eidelmaim** [TheCBProject/EnderStorage#2]
would be really nice/cool to have a upgradeable ender pouch that has filters which will allow you to assign an item, this item would than be magically moved from your inventory to the ender pouch. applications could include long mining sessions where you have a ender chest at your base outputting its items into another storage such as a AE system or a pipe filtered BC system.

**Comment by covers1624** [comment]
Interesting, It would have to be on item pickup sadly, I'll get back to you once I bounce the idea off ecu and cb.

**Comment by Eidelmaim** [comment]
Item pickup would work best, and maybe two tiers of upgrade, one that uses item filter, and one that does anything you pick up, make it a toggle feature, shift click type thing,

**Comment by Ecu** [comment]
Not that I truly have any direct say in where this mod goes, as it's originator I want to say that I've always felt that enhancements like this are out of place in Ender Storage.  This mod has always been designed to be a simple means in which to transport items (and/or liquids) between locations.  

Adding mode-based items or enhancements like this is really out of place.

**Comment by covers1624** [comment]
That's fair enough.
Ecu, considering you are the mods originator you basically have the final say.
So, in conclusion, this will not be added as the mod is meant to be simplistic. If another mod wants to come along and allow auto picking up in to the bag with a bauble or something that is fine.

**Comment by Eidelmaim** [comment]
Very much sad face 😞, but I respect your wishes, I might have a stab at developing a mod to compliment this.

**Comment by Ecu** [comment]
Honestly, my personal believe is that you're automating TOO much.  It isn't all that hard to just dump a bunch of stuff into the Ender Pouch as you mine.  Hell, I somewhat regret adding the pouch simply because of how easy it is to use already.

That said, by all means make your own mod to add this.  It probably won't be non-trivial though as you'll have to account for multiple Ender Pouches being in the inventory, be able to access the correct inventory storage for the correct pouch, etc.  Honestly not sure how many hooks @covers1624 has made to accommodate for an addon like this.

**Comment by Eidelmaim** [comment]
What I'm thinking is adding a new pouch that is separate from the original pouches that will have these features that can be connected to ender chests, won't have to worry about how many other original ender pouches are in the inventory.

**Comment by Ecu** [comment]
Ah.  That could indeed work.  The color code (and as such the storage) should be reasonably easy to get and ES is open source, so have at it.

I will say though, that I feel that the more you automate, the quicker you will find that the fun gets drained out of the playthrough and you find yourself wanting to start over.  After a few hundred times of starting over, you may find yourself completely disillusioned with Minecraft like I, myself, have.

**Comment by covers1624** [comment]
i would do it the other way, basically you have some sort of amulet or bauble on your hot bar then on item pickup event if the player has that amulet in their hot bar, check the entire inventory for the first ender pouch you find, then grab the Frequency from the itemstack then grab the storage then insert the items in to the inventory. Simple. By the sounds of it you are new to modding / programming, so i would advise against making a whole new pouch as layered models are more difficult than they were back in 1.7.10 so it would be a big task. I do however highly reccomend using CCL's inventory utilities as it will make your life easier. Also to improve efficiency i would search for a pouch and the amulet in one iteration.

**Comment by Eidelmaim** [comment]
@ECU I agree, some people burn them selves out with automation, yet other people live by it as I do, people always have a choice in how they want to do things.

@covers1624 yes, I am as new as they get to modding so this will take me loads of time to figure out but I am determined, I have ideas about addons for other mods as well so I have to start somewhere, as for which version, I will be working with 1.7.10 to begin with, primarily due to the server i manage is not advancing past that version for the foreseeable future.

**Comment by Ecu** [comment]
To each their own, for sure.  You can hit me up on twitter (via DM, preferred) or at #Redux on Esper if ya want to discuss further.  Wish ya the best.
