### ISSUE TITLE
[1.10.2] Ender Pouch has invisible texture

### ISSUE THREAD

**Issue by Morpheus1101** [TheCBProject/EnderStorage#20]
When viewing the EnderPouch both in JEI and in inventory, it has an invisible texture...The pouch if you know what slot it is in, will work quite fine.

Enderstorage:  2.1.5.82
Forge *.2107
CCL: 2.4.2.106
CCC: 2.3.4.89

As yet i havent gone through an tested this on its own or added mod by mod to see which one maybe causing this issue.

**Comment by ygaeon** [comment]
I just discovered this myself, but I couldn't find the pouch in my inventory (mouse-over every slot, no tooltip) nor could I craft it using JEI.

I was on "All the mods" version 1.10.2 1.42b (currently updating to 1.43 alpha).

**Comment by covers1624** [comment]
Can I have your log, it will only do this if the model baking thread fails.

**Comment by ygaeon** [comment]
@covers1624 -- unfortunately I already updated and restarted the client. After restart it worked as intended again, but I had to recreate the Ender Pouch as it was nowhere to be found. Perhaps @Morpheus1101 have a log for his particular issue?

**Comment by covers1624** [comment]
This crash shouldnt happen as of https://github.com/TheCBProject/CodeChickenLib/commit/16d29344f048fbdd1eddd44f3d8118decd320af3
