### ISSUE TITLE
Crash when dropped entities from Ender Storage attempt to render

### ISSUE THREAD

**Issue by TheRealBrobie** [TheCBProject/EnderStorage#200]
Crash when dropped entities from Ender Storage attempt to render.

MC: 1.19.2
Forge: 43.1.3

See crash log below.

[crash-2022-08-30_18.13.39-client.txt](https://github.com/TheCBProject/EnderStorage/files/9457124/crash-2022-08-30_18.13.39-client.txt)

Single player offline world using a modpack I made just for myself.

I ran through many iterations removing mods until I could properly play again and it appears that Ender Storage is the culprit. The first crash occurred when I died in the nether with an Ender Pouch and attempted to retrieve it. Every time I got within render distance of my items, the game would crash.

I gave up, crafted an ender chest to get my stuff from the lost pouch and when I went to break the Ender Chest, the game crashed again. This led to the realization that it must be the Ender Storage mod.

**Comment by TheRealBrobie** [comment]
I just wanted to add, one of my iterations removed Rubidium, Oculus, and the Rubidium extras and things since those modify the rendering processes and I still received the crash.

**Comment by TheRealBrobie** [comment]
I should have done this all before my initial post but I just started a brand new Creative world, gave myself a diamond pickaxe and ender chest, placed the chest, went to survival mode and mined the chest and the game instantly crashed. Crash in console always begins with the following line:

[minecraft/Minecraft]: Unreported exception thrown!
java.lang.IllegalStateException: Pose stack not empty

**Comment by covers1624** [comment]
Does this only occur with EnderStorage and CCL installed?

Can you please provide your full debug.log?

**Comment by TheRealBrobie** [comment]
This was the debug log from my Creative world. If you need me to recreate with my main world, I can as well.

[debug-1.log.gz](https://github.com/TheCBProject/EnderStorage/files/9457653/debug-1.log.gz)

**Comment by TheRealBrobie** [comment]
Can confirm, started a new instance with only Forge, CCL, and EnderStorage installed and was able to recreate the crash.

[debug.log](https://github.com/TheCBProject/EnderStorage/files/9457697/debug.log)
[latest.log](https://github.com/TheCBProject/EnderStorage/files/9457698/latest.log)

**Comment by covers1624** [comment]
This should be resolved by updating CCL to [this version](https://maven.covers1624.net/codechicken/CodeChickenLib/1.19.2-4.3.0.470/CodeChickenLib-1.19.2-4.3.0.470-universal.jar). CurseForge approval pending.

**Comment by TheRealBrobie** [comment]
Thanks for the quick fix. I updated and it works like a charm now. Cheers!
