### ISSUE TITLE
Ender storage item and blocks crash

### ISSUE THREAD

**Issue by Thollp** [TheCBProject/EnderStorage#208]
For some reason, the game crashes when I go to automatic shaped crafting from "Create" mod of the item or block's recipe and when I press u while hovering curser to any of the item or blocks from the mod like the issue #206

**Crash log/report**

https://pastebin.com/ReTXcdQf

**Step to reproduce the Bugs/Crash:**
1. Load the minecraft as normal.
2. Go to inventory.
3. hover mouse on any items from EnderStorage mod.
Option 1 of step 4. Press u
Option 2 of step 4. Click r and go to automatic shaped crafting.
5. Crash.

**Anything else?**
This bug was cause by the mod "create" and JEI. I know because the mod "not enough crash" was installed too, and I want you to take a closer look at the crash log how it break the game and fix the mod.

Btw I play MC java via pojavlauncher so the system detail of my device in crash report might look odd.

**Comment by Thollp** [comment]
*Just hope devs will stumble upon this issue*

**Comment by covers1624** [comment]
Please provide a crash report.

Simply submitting an issue stating its broken without providing any logs, mod version numbers, or reproduction steps, is like walking into the Mechanics and asking them to fix your car, whilst leaving it at home.

**Comment by Thollp** [comment]
> 

Ah, I forgot =(

**Comment by Thollp** [comment]
> Please provide a crash report.
> 
> Simply submitting an issue stating its broken without providing any logs, mod version numbers, or reproduction steps, is like walking into the Mechanics and asking them to fix your car, whilst leaving it at home.

Oh, I forgot. I'll put it later

**Comment by covers1624** [comment]
I have received no logs. Closing.

**Comment by Grath** [comment]
I've been having issues with this bug in my modpack. [Here's a log of the resulting error which happens any time you check usages of Ender Storage items with JEI, reproduced in a minimal environment.](https://mclo.gs/kNwMDtL) Environment used to reproduce bug:

- Minecraft 1.19.2
- Forge 43.2.14
- CodeChicken Lib 4.3.1.481
- Create 0.5.1.b
- EnderStorage 2.10.1.181
- Just Enough Items 11.6.1016

These are the latest versions of EnderStorage, Create, and JEI, paired with the latest versions of Forge and EnderStorage's listed dependency of CodeChicken Lib; no other mods are even loaded.

Steps taken to reproduce bug:

- Open a singleplayer (or multiplayer) world.
- Open your inventory and search up Ender Storage items in JEI.
- Right-click or press 'u' on an Ender Storage block, such as the Ender Tank.
- Game immediately crashes every time.
