### ISSUE TITLE
[1.10.2] Load error - java.lang.NoSuchFieldError: verts

### ISSUE THREAD

**Issue by MakerTim** [TheCBProject/EnderStorage#21]
I try to startup EnderStorage, but it fails and gives me this crashlog

http://pastebin.com/AUMhA1EZ

CodeChickenCore-1.10.2-2.3.4.89-universal
CodeChickenLib-1.10.2-2.4.2.106-universal
EnderStorage-1.10.2-2.1.5.80-universal
AND
EnderStorage-1.10.2-2.1.5.82-universal

**Comment by Ezoteric** [comment]
same with newest version

**Comment by covers1624** [comment]
Remove the old version of ccl from /mods/1.10.2/
