### ISSUE TITLE
[1.12.2] Error Executing Task

### ISSUE THREAD

**Issue by InuYasha86000** [TheCBProject/EnderStorage#219]
Thanks to Vanilla Tweaks the game does not crash, but I get a warning of an error: java.util.concurrent.ExecutionException: java.lang.NullPointerException

here is the log file from it
[crash-2023-05-23_21.57.03-server.txt](https://github.com/TheCBProject/EnderStorage/files/11550550/crash-2023-05-23_21.57.03-server.txt)

**Comment by covers1624** [comment]
Unfortunately, 1.12.2 is not supported anymore.
