### ISSUE TITLE
Modrinth release?

### ISSUE THREAD

**Issue by lonevox** [TheCBProject/EnderStorage#224]
Could this be uploaded to Modrinth? It is one of the only mods in my pack that isn't on Modrinth so an upload there would be awesome! If a Modrinth release isn't planned, is it okay to distribute your jars in my pack (the actual jar file, not a link)?

**Comment by ghost** [comment]
I guess this issue can be closed now: https://modrinth.com/mod/ender-storage

**Comment by covers1624** [comment]
Correct, the mods are now dual released on Modrinth.
