### ISSUE TITLE
1.20 version

### ISSUE THREAD

**Issue by dhouck** [TheCBProject/EnderStorage#225]
I donʼt know much about mod development so maybe itʼs harder for this mod than Iʼd expect, but are there plans to make a 1.20+-compatible version?

**Comment by baseballjustin5** [comment]
There is at least a 1.20.1 version as of May 14th!

**Comment by covers1624** [comment]
I forgot this issue existed.

1.20.1 versions have been released.

**Comment by Sebz102030** [comment]
1.20.1 version throws error in inventory with ender storage
