### ISSUE TITLE
CodeChicken Lib not listed as required dependency on Modrinth

### ISSUE THREAD

**Issue by MelanX** [TheCBProject/EnderStorage#227]
[Ender Storage 1.20.1-2.11.0.188](https://modrinth.com/mod/ender-storage/version/2.11.0.188) does not have CodeChicken Lib as dependency listed. Because of that, it's not downloaded automatically.

**Comment by covers1624** [comment]
This should be fixed. Appears there is _another_ bug in the new publishing stuff ._.
