### ISSUE TITLE
[1.10.2] EnderChest Loses Colorings with redstone signal?

### ISSUE THREAD

**Issue by Morpheus1101** [TheCBProject/EnderStorage#23]
When i added the leaver to this machine as u can see the colors for the 3 parts were set black blue black .. Once the lever was turned on, the colors r reset to all white, however it is still linked to the Black Blue Black

![before](https://cloud.githubusercontent.com/assets/10524952/20233150/35c98ff4-a8b9-11e6-9526-a06b3e3211a6.png)
![after](https://cloud.githubusercontent.com/assets/10524952/20233161/3aa9ff86-a8b9-11e6-85eb-fa90ce65b187.png)

**Comment by covers1624** [comment]
Odd, it also resets the tiles rotation, can you confirm that the rotation is still broken after reload / relogging.

**Comment by Morpheus1101** [comment]
Yes, after a server reboot and re-join, everything is as shown in the bottom picture

**Comment by covers1624** [comment]
Hmm, I'll poke arround it when I get back.

**Comment by covers1624** [comment]
Does this still happen?

**Comment by Morpheus1101** [comment]
I'll have to test when i get back up to bein able to use Ember machines

**Comment by covers1624** [comment]
If it happens again, new issue.
