### ISSUE TITLE
Crash on modpack load

### ISSUE THREAD

**Issue by the-creamster** [TheCBProject/EnderStorage#24]
https://github.com/suranis/TC-Expert-Mode-Modpack/issues/1 (prviate repo atm, working on it)

**Comment by covers1624** [comment]
Ill respond on the CCL issue tracker

**Comment by the-creamster** [comment]
Ok to begin with i'm getting the following crashes at different stages of pack loading(normally around stage 2/3) with my one which is tweaked off the previous working build. The strange thing about it is that i can launch the pack by the other admin which has identical mod versions and it doesn't crash on me.

The order in which they were crashing seem to correspond to the mod loading order:

Draconic Evolution
Ender Storage
Immersive Engineering
Translocators
CodeChicken Lib
Crash Reports
Draconic Evolution: https://gist.github.com/the-creamster/f61988d0bd1ec74a0d7f3012649cce99
CodeChicken Lib: https://gist.github.com/the-creamster/125991568c9fa3cf3681ee58a470d777
Translocators: https://gist.github.com/the-creamster/2cb3fe5103e13f50497319952dc749fb
Immersive Engineering: https://gist.github.com/the-creamster/f168aba00ebe944ef86645abd0768ee4
Ender Storage: https://gist.github.com/the-creamster/da52b6bbeb67637a62ecf4b27a8e7c6f

Any thoughts as to why my tweaked pack crashes and the other one with identical version isn't???
Cheers, The_Creamster.

I linked to the issue on the repo which was private(didn't realise that meant links to it appeared broken) due to the size of the initial post.

**Comment by covers1624** [comment]
Deleate the duplicated version of CCL inside your /mods/1.10.2/ folder

**Comment by the-creamster** [comment]
What duplicate version??? i only see 1 of them

**Comment by covers1624** [comment]
It is inside /mods/1.10.2

**Comment by the-creamster** [comment]
https://gyazo.com/b2b319b7aaa4df4eebcee2bfeb11505a

**Comment by covers1624** [comment]
That is the duplicate. Delete it.

**Comment by covers1624** [comment]
https://puu.sh/sptgI/5344c88a2c.png

**Comment by the-creamster** [comment]
ok, that may explain codechicken lib; but what about the other crash reports its generating that are normally located??

**Comment by covers1624** [comment]
It is all due to the Duplicated CCL versions, Everything there exept ImmersiveEngineering uses CCL and the crashes are a direct result of duplicated CCL.

**Comment by covers1624** [comment]
If IE is still crashing, report it to them.
