### ISSUE TITLE
[Feature Request] Toggle global EnderStorage

### ISSUE THREAD

**Issue by Mohron** [TheCBProject/EnderStorage#26]
Hi I would like to know if you would be willing to add a config option that disables the global/shared ender chests.  If this setting was utilized, chests crafted could either not work before being made private or more efficiently just have the recipe output a private chest automatically. Handling owner changes could be done by crafting a chest by itself. This would help heavy progression themed packs run on servers combat using ender chests to get around other protections put in place to prevent sharing outside your team.

Thank you for your consideration!

**Comment by covers1624** [comment]
@Ecu Thoughts?

**Comment by ktole1999** [comment]
then just disable the chest.

**Comment by Mohron** [comment]
@ktole1999 Ender Chests are incredibly useful and I am not interested in removing player's access to them completely. The would not serve my intentions. I personally use Ender Chests in every pack that includes them, yep I never use any of the 4096 global chests since I make my chests private immediately.

**Comment by covers1624** [comment]
I like the idea, just need to run it by the higher ups. hence why ecu was ponged.

**Comment by Mohron** [comment]
I'd like to point out that this could and should be extended to the bags & tanks if implemented :)

**Comment by Ecu** [comment]
Sorry, didn't notice this until now.  Hrm, I don't really see an issue with an optional config to make all items private by default with no global option at all if the flag is set.  Probably also do the opposite and have a global only option as well.

If pack authors feel the crafting costs need to be changed, I feel there are probably enough recipe changing mods out there to handle that, so we don't need to much with the recipes at all (beyond disabling private/public depending on the flag).

**Comment by covers1624** [comment]
Right, what i was thinking is, on place its just auto locked, and forced to stay that way. So, if someone still has a unlocked chest down, then replace.

**Comment by Mohron** [comment]
@covers1624 I just would only lock a chest/tank to a player on the first placement so users can share their locked chests/tanks like they can currently.

**Comment by Ecu** [comment]
Sure.  Works for me.  It would also need to automatically cause all pouches to use their private frequency only, rather than the public one.  I'll leave it in your capable hands as to how to make it work effectively.

**Comment by covers1624** [comment]
Yep, i have some ideas on how to pull this off nicely.

**Comment by covers1624** [comment]
This will be done in 1.11 as i have changes to the back end planned to make the implementation of this less hacky.

**Comment by covers1624** [comment]
https://github.com/TheCBProject/Feedback/issues/8
