### ISSUE TITLE
can you update EnderStorage let it  versus CodeChicken Lib 1.10.2-2.5.4.218-universal Compatible

### ISSUE THREAD

**Issue by RebelliousAngels** [TheCBProject/EnderStorage#29]
can you update EnderStorage let it  versus CodeChicken Lib 1.10.2-2.5.4.218-universal Compatible

sorry i am Taiwanese  English NOT GOOD

they incompatible and i can't see Ender backpack skin

**Comment by RebelliousAngels** [comment]
i update Draconic-Evolution-1.10.2-2.0.8.177-universal   CodeChickenLib-1.10.2-2.5.4.218-universal

BrandonsCore-1.10.2-2.1.4.92-universal  EnderStorage-1.10.2-2.1.5.84-universal

i can't see Ender backpack skin  but  i can use backpack

**Comment by covers1624** [comment]
Fixed agaes ago.
