### ISSUE TITLE
Strange Rendering Bug

### ISSUE THREAD

**Issue by TwitchtvCarbs** [TheCBProject/EnderStorage#31]
Version 1.11.2-2.3.0.112-Universal

Seem to be having a strange rendering bug with the ender tanks (See gif) It works great just a small rendering bug I thought  I should let you know! It seems when you get a few buckets in to filling the tank it then stops filling and goes back down to the bottom.

https://gyazo.com/b9a478350712ddae99eb05545be68c3b

**Comment by covers1624** [comment]
Fixed in dev.
