### ISSUE TITLE
EnderStorage-1.10.2-2.2.1.106-universal causes rendering glitch

### ISSUE THREAD

**Issue by UnixRonin** [TheCBProject/EnderStorage#32]
There seems to be a rendering bug on the Ender Chest that causes other blocks to sometimes become semi-transparent when an Ender Chest is in the field of view, even if the Ender Chest is obscured behind other blocks or under a floor. Observe in screenshot https://www.caerllewys.net/public/minecraft/2017-04-27_10.44.32.png how the two chests visible in the nearest row of RR storage units are semi-transparent; there is an ender chest out of direct line of sight, but within field of view, obscured behind the marble stairs on the right.  Standing in the same spot and turning just slightly to put the hidden ender chest outside FOV, https://www.caerllewys.net/public/minecraft/2017-04-27_10.44.35.png suddenly the chests display normally again.  They also return to normal if the ender chest is removed.

I have observed this with chests, stone blocks, and various mod blocks and items, both placed in the world and blocks that are rendered in 3D by the storage units. It seems somewhat random which blocks will become transparent, and they are typically transparent only from certain directions and distances, but if a block is transparent from a certain distance and direction it will always be transparent from that distance and direction.

**Comment by UnixRonin** [comment]
Not sure why my links aren't working there...

**Comment by covers1624** [comment]
I don't believe this is EnderStorages fault, If it were, the issue would be happening for almost everything. Its probably an issue with What ever mod is rendering those chest items may be the cause.

**Comment by UnixRonin** [comment]
Sorry, I thought I updated everywhere else but forgot to update here.  The author of Router Reborn determined that the problem was actually in his router rendering, but it appeared at first to be the ender chest because it only occurs when an ender chest is present within the field of view as well.

**Comment by covers1624** [comment]
Ah, Glad its fixed.
