### ISSUE TITLE
** [1.10.2] Ender Pouch has invisible texture #20

### ISSUE THREAD

**Issue by ktole1999** [TheCBProject/EnderStorage#34]
does this mean updating CCL will resolve the texture issue?

**Comment by covers1624** [comment]
You have provided no info no what versions you are running, how am I supposed to know? You will need to provide more info if I am to help you.

**Comment by ktole1999** [comment]
i needed clarification on your post here about the fix. https://github.com/TheCBProject/EnderStorage/issues/20

**Comment by covers1624** [comment]
Yes, this was fixed long ago, update your mods.
