### ISSUE TITLE
1.11.2-2.3.0.112-Universal Ender Pouch Crashing When Full

### ISSUE THREAD

**Issue by TwitchtvCarbs** [TheCBProject/EnderStorage#36]
Having a client side crash when the player tries to shift click items into their ender pouch when it is already full.

See crash report here:
https://pastebin.com/samqeXqC

**Comment by covers1624** [comment]
Duplicate, fixed in dev pending release.

**Comment by TwitchtvCarbs** [comment]
Awesome! Keep up the good work guys :)
