### ISSUE TITLE
Can't place translocators on Enderchest 1.11.2

### ISSUE THREAD

**Issue by Fundryi** [TheCBProject/EnderStorage#39]
As the title says, I think it's just because U can open the ender chest even if u sneak right click.

Minecraft: 1.11.2
Forge: Newerst
EnderStorage: Newerst

if you need more information please tell me. :D!

**Comment by covers1624** [comment]
Right, Translocators issue, Im getting arround to that. Translocators doesnt support the forge cap system. Yet.
