### ISSUE TITLE
1.9.4 ender pouch is out of sync with ender chest after updated to 2.0.3.62

### ISSUE THREAD

**Issue by LordHellscream** [TheCBProject/EnderStorage#4]
Just updated to 2.0.3.62, my existing WWW pouch is out of sync with my WWW ender chests. I tried recreating the pouch and same result, it seems like it created a different storage with dupe items

**Comment by covers1624** [comment]
@gigabit101 This the same issue that you saw?

**Comment by LordHellscream** [comment]
Looks like this have something to do with being in different dimension. 
I have one color of chest (WWW) for all my input,. I have a WWW to receive output from rftools builder quary from a rftools dimension, another few WWW chests inside my base (in overworld) for ore processing/mob farm etc.
This was working perfectly before, but it seems like after i updated, the chest in the rftools dimension somehow become another chest, since my WWW pouch is somehow still linked to the WWW chest in the other dimension. it appears it is out of sync with the WWW chest(s) in my base. but it appears its still in sync with the one chest in other dimension.
However, all my WWW chests in my base still sync with each other..
it sounds like even tho all these WWW chests are same color, somehow, after the update 2 different "channels" were created...

**Comment by gigabit101** [comment]
Yeah same sort of issue not tried cross dimensions yet

**Comment by LordHellscream** [comment]
I temporarily fixed this by replacing my ender chests in the base (any newly built chest/pouch are synced to the chest in the other dimension). but it only last until i exit the game. after reloading the save, the chests in the base are out of syncs (with the ones in the other dimension again).
