### ISSUE TITLE
1.10.2 Items not stacking with other like items in ender chest.

### ISSUE THREAD

**Issue by Hazmatik** [TheCBProject/EnderStorage#40]
If items are inserted into an Ender Chest and there is already some of the same item in there but there is an empty slot before the slot those items are in the item goes to the empty slot instead of stacking with the other same items.

This GIF shows an example I have an ender chest set up to dump things into my storage, yet a lot of it isn't getting put in cause like items are coming in and getting placed in the empty slots at the top instead of adding to the partial stacks of the same item.

[![https://gyazo.com/7bd14f72b23130c94a483f56ada8d0d4](https://i.gyazo.com/7bd14f72b23130c94a483f56ada8d0d4.gif)](https://gyazo.com/7bd14f72b23130c94a483f56ada8d0d4)

**Comment by covers1624** [comment]
Issue with what ever is doing the inserting. ES is just an inventory.
