### ISSUE TITLE
Ender Storage 1.10.2 won't load because CodeChickenCore not Recognized?

### ISSUE THREAD

**Issue by katubug** [TheCBProject/EnderStorage#41]
I've attached a screenshot of the error, and of my mods folder. This also happens when I use the previous version of the CodeChickenLib. Maybe this is the wrong place to post this - if so, please let me know.

![enderstorage issues](https://user-images.githubusercontent.com/20935286/27843922-c1c2f318-60df-11e7-843c-f9144cda98ea.jpg)

**Comment by covers1624** [comment]
Yeah, so, CodeChickenLib and CodeChickenCore arent the same thing, in 1.11 CCC is dead, but in 1.10 you need both.

**Comment by katubug** [comment]
Oh, my bad. I just downloaded what was linked via the Curse page. I'll go download the proper thing, then. Thanks for pointing me in the right direction, really appreciate it!
