### ISSUE TITLE
[1.12] Crash on Launch

### ISSUE THREAD

**Issue by nightcipher** [TheCBProject/EnderStorage#43]
Using the latest build of EnderStorage from the ChickenBones.net, the launcher crashes during the Forge mod-loading process. 

Forge ModLoader version 14.21.1.2406

Crash log file:
[crash-2017-07-10_12.54.00-client.txt](https://github.com/TheCBProject/EnderStorage/files/1136429/crash-2017-07-10_12.54.00-client.txt)

Launcher log file:

[latest.txt](https://github.com/TheCBProject/EnderStorage/files/1136426/latest.txt)

**Comment by covers1624** [comment]
You need to update CCL.
