### ISSUE TITLE
Cannot put a diamond on the latch of an ender storage chest

### ISSUE THREAD

**Issue by Captainaviator** [TheCBProject/EnderStorage#45]
I'm not sure if this has been re-implemented yet, but on 1.11, nothing happens when right clicking with a diamond on the latch (it just opens the chest), both sneaking an non sneaking.  I also tried aiming it at different sides of the latch.

**Comment by covers1624** [comment]
Interesting, do you see the bounding box of the latch?

**Comment by Captainaviator** [comment]
I believe I see it if I'm aiming at the top of the latch, but not if I'm aiming at the front

**Comment by covers1624** [comment]
1.11 is no longer supported sorry, 1.12 works fine.
