### ISSUE TITLE
Crash on 1.12 when loading in a world (version 1.12-2.4.0-119-universal)

### ISSUE THREAD

**Issue by mrtopf** [TheCBProject/EnderStorage#46]
Here is the crash log: 

https://gist.github.com/mrtopf/fc41fa5b1e169624cf952f049f6d94c3

( I deleted some mods before that but their item shouldn't have been in any inventory if that is important to know).

**Comment by mrtopf** [comment]
also looking at the code: I might have changed the chest size in the config after creating chests. I am just not sure if I didn't start the world after the change or not.

**Comment by covers1624** [comment]
Found the issue, fixed in dev.
