### ISSUE TITLE
Ender chests white/white/white and facing the wrong way

### ISSUE THREAD

**Issue by Ricket** [TheCBProject/EnderStorage#48]
EnderStorage-1.11.2-2.3.1.116-universal, in modpack All the Mods 2 v0.73.

I placed these chests down:
![image](https://user-images.githubusercontent.com/196978/28732528-2c59e488-73a6-11e7-8fdc-ec3a74b9e44c.png)

But after logging out and back in, the chests are blank and facing the wrong way, and also the vanilla chest in front of them is disappeared for some reason.

![image](https://user-images.githubusercontent.com/196978/28732580-585f0b3a-73a6-11e7-9ace-8762a93e4fc4.png)

And then if I just move/look around a bit, it pops into existence:

![image](https://user-images.githubusercontent.com/196978/28732619-74204802-73a6-11e7-95bd-5069c79d9939.png)

If I break the chests, I get the correct colored ones and can place them back down and they're ok til the next login.

**Comment by covers1624** [comment]
This is almost definitely the client tile being corrupted by another mod somehow, do you have any harvest craft blocks nearby?

**Comment by Ricket** [comment]
Why harvestcraft in particular? We have a couple of ground traps nearby. That's the only thing that comes to mind. I can't log in for another day or more so I can't experiment in person yet.

**Comment by covers1624** [comment]
I recently tracked down client side tile issues to harvest craft, a pr has been pushed and accepted for 1.12. Basically when the chunk is sent to the client, harvest craft was failing to read its tile data causing all other tiles in the chunk to not be loaded only on the client.
