### ISSUE TITLE
Cannot sync an ender pouch with the color code of an ender chest

### ISSUE THREAD

**Issue by Captainaviator** [TheCBProject/EnderStorage#49]
I color coded my ender chest, and nothing happens when i sneak-right click on it with my ender pouch.  It just opens the chest.  Same thing with sneak left clicking and non-sneak right and left click.  I also tried aiming at different parts of the chest (color things on top, latch, etc).  I'm on the 1.11 version.

**Comment by covers1624** [comment]
Works fine in 1.12, 1.11 is no longer supported sorry.
