### ISSUE TITLE
[1.12] EnderChest Loses Colorings with redstone signal when connected to Embers Bore

### ISSUE THREAD

**Issue by Morpheus1101** [TheCBProject/EnderStorage#50]
Exactly the same as my previous reported issue https://github.com/TheCBProject/EnderStorage/issues/23

https://puu.sh/wW7b6/802cb540d9.mp4

**Comment by magneticflux-** [comment]
@Morpheus1101 What multiblock is that connected to? I just tried to reproduce with a bare redstone signal and nothing happened. Is the multiblock designed to interface with the chest in some way to include it?

**Comment by Morpheus1101** [comment]
Its connected to an Embers Bore in which the Ember Shards are output into the chest and no with a standard signal on the chest alone this does not occur.  This is something covers an i have discussed and an odd thing.

**Comment by magneticflux-** [comment]
@Morpheus1101 Could you raise an issue on the [Embers mod GitHub](https://github.com/RootsTeam/Embers)? Their developers might be able to provide some insight into what actions are performed. I don't think it's their fault necessarily, but by linking this issue to a new one on their repo they might help get a fix quicker.

**Comment by covers1624** [comment]
Fairly certain this is embers breaking my tile somehow. Report it to them.
