### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ktole1999** [TheCBProject/EnderStorage#51]
I have crashed 5 times today with this error. i have tried restarting. i have deleted the enderchest i was looking at when crash occurred but it happened again while looking at another chest.

https://gist.github.com/ktole1999/25a966f8b4509882468d3607755fea6c#file-crash-2017-07-29_12-00-27-client

**Comment by covers1624** [comment]
This is literally out of my control, im adding data to a buffer that i have no control over and its apparently full when its meant to grow, remove optifine and try again, short of that, update your video card drivers.

**Comment by ktole1999** [comment]
everything has been working fine for months without any pack/system changes and all of a sudden its either optifine or video drivers. ok if you say so. you are the dev.

**Comment by Ricket** [comment]
By definition, something must have changed for you to be suddenly experiencing this crash. Are you experiencing any other different crashes? What kinds of things did you build in the world recently?

edit: nevermind, begin calls reset. Beats me...

**Comment by ktole1999** [comment]
nothing recently built. as i mentioned i have been playing the same area,  same machines for months. out of the blue i get all these crashes.
