### ISSUE TITLE
Enderchests have strange names, along with endertanks

### ISSUE THREAD

**Issue by Akitori** [TheCBProject/EnderStorage#52]
Not really a issue so much as a lang problem i am guessing. Enderchests are called

tile.ender_chest.name

and tanks are 

tile.ender_tank.name

**Comment by 016Nojr** [comment]
https://github.com/TheCBProject/EnderStorage/pull/47

**Comment by covers1624** [comment]
Fixed: https://github.com/TheCBProject/EnderStorage/commit/58c1791c5809736e8cb3980a95fd3cbb36dbfc62
