### ISSUE TITLE
Inventory Tweaks support absent

### ISSUE THREAD

**Issue by magneticflux-** [TheCBProject/EnderStorage#54]
Inventory Tweaks support is completely missing from the 1.12 version. Sorting and other features do not work in ender chests or bags.

To support Inventory Tweaks, simply add the interface from their API (located [here](https://github.com/Inventory-Tweaks/inventory-tweaks/blob/develop/src/main/java/invtweaks/api/container/ChestContainer.java)) to the ContainerEnderItemStorage class.

**Comment by magneticflux-** [comment]
@covers1624 I'm working on a PR that fixes it. It should be done in a day or two since I just got sorting working for a single test case.

**Comment by Matakor** [comment]
Is it possible to add support to 1.10/1.11 as well?

**Comment by covers1624** [comment]
Im not pushing any more updates for 1.10 and 1.11, 1.12 is the place to be, it's time to move on.

**Comment by covers1624** [comment]
https://github.com/TheCBProject/EnderStorage/commit/1059692e093f603122e487140455686a7972bc8d
