### ISSUE TITLE
Ender Chests/Tanks lose personal label when broken 1.10.2

### ISSUE THREAD

**Issue by orionSquared** [TheCBProject/EnderStorage#57]
Good evening,

It seems that when I place down both the ender chests and tanks, and then apply a diamond on them to put them on my personal network and break them to pick them back up, they are losing the personal network data. When I place them back down, the clasps are back to gold rather than diamond

**Comment by covers1624** [comment]
Appears to work fine for me, check your config and make sure you don't have anarchy mode turned on.
