### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Miner94** [TheCBProject/EnderStorage#58]
is it possible to add support for mekanism gasses like you have the fluid tank

**Comment by covers1624** [comment]
Im not entirely sure what you mean, as in for crafting? placing in world, glasses as in a wearable item that mekanism has?

**Comment by Miner94** [comment]
no ok let me clarify allitlle so you kno how the ender tank can transfer over long distances or even across dimensions i was thinking adding a tank with that same functionality but for gasses

**Comment by covers1624** [comment]
Oh gas not glass. Well if their gas is just a normal fluid then it will work fine..

**Comment by Miner94** [comment]
not makansim doesnt do it ive tried lol

**Comment by Miner94** [comment]
right now i kno a way around but its a hassle and it eats thru resources

**Comment by covers1624** [comment]
No sorry, The forge fluid implementation supports fluids that are gases and there is absolutely no reason to have a custom implementation. EnderStorage was always meant to complement vanilla and adding direct mod support is something im not going to do as i wish to respect Ecu's wishes. Mekanism should use forges fluid implementation.
