### ISSUE TITLE
Compatibility: use oredict:chest for Ender Chest

### ISSUE THREAD

**Issue by Xiaminou** [TheCBProject/EnderStorage#59]
Change vanilla only chest in the Ender Chest recipe to oredict:chest (or chestwood) to improve compatibility with mods that add chests such as Quark.
![2017-11-07_19 00 37](https://user-images.githubusercontent.com/8670392/32509575-f89bed1a-c3ed-11e7-8eaa-0d1a03ecc94c.png)

**Comment by covers1624** [comment]
Took me a few miniutes to figure out what you were saying. If I'm correct, you want oreDict support for the chest input of ender storage recipes? Also what mc version are you on.

**Comment by Xiaminou** [comment]
That's correct, sorry if I wasn't clear.
I'm on 1.12.2. But should probably do it for as many versions as possible.
