### ISSUE TITLE
Crash on joining server 1.12.2

### ISSUE THREAD

**Issue by Seceroth** [TheCBProject/EnderStorage#60]
Hello,

As the title says, my client crashes when I try to join my family server with EnderStorage installed. The server keeps running just fine with no error other than that a disconnect happened by the client (Connection reset by peer).
I saw EnderStorage mentioned in the log and removing this mod from the server and client does let me log in to the server.

The crash-report:
[crash-2017-11-09_09.44.45-client.txt](https://github.com/TheCBProject/EnderStorage/files/1456972/crash-2017-11-09_09.44.45-client.txt)

**Comment by covers1624** [comment]
Do you happen to be running sponge on your server?

**Comment by Seceroth** [comment]
Yes, running spongeforge-1.12.2-2529-7.0.0-BETA-2729.

**Comment by covers1624** [comment]
I've added some checks so this shouldnt happen.
