### ISSUE TITLE
[1.10.2] Wrong language translation in zh_tw

### ISSUE THREAD

**Issue by hugoalh** [TheCBProject/EnderStorage#63]
The language translation in 1.10.2 is wrong, and I found that the previous translator have mix up the name of ender chest and ender tank.
The file is the fixed lang files for zhtw.

[enderstorage_zhtw.zip](https://github.com/TheCBProject/EnderStorage/files/1586501/enderstorage_zhtw.zip)

**Comment by covers1624** [comment]
Hi, are you able to open a Pull Request for this targeting 1.10, 1.11 and 1.12?

**Comment by hugoalh** [comment]
As I have sign up GitHub for nearly 4 months, I still don't know how to make a pull request...😂
I am not a programmer...

Edit: I tried to make pull request, hope no things wrong...

**Comment by covers1624** [comment]
Pr pulled.
