### ISSUE TITLE
I have no idea what's going on here and no idea what to even call it. 

### ISSUE THREAD

**Issue by Jerria1** [TheCBProject/EnderStorage#67]
It seems as if the ender chest are causing weird shimmers in the sky and it makes the chest look all weird. Seeming that the ender chest is the only thing affected by it, I assume it is this mod that caused it.
![2017-12-27_12 04 41](https://user-images.githubusercontent.com/34838722/34443525-637c2e5c-ec8d-11e7-886a-e50ca7b24783.png)

**Comment by covers1624** [comment]
I was never able to reproduce this, It was likely some other mod breaking the GL state, i pop everything back that i touch, if it happens again, please open another issue.
