### ISSUE TITLE
Ender Chests render not properly and do damage

### ISSUE THREAD

**Issue by ThexXTURBOXx** [TheCBProject/EnderStorage#7]
Some things can render through Ender Chests:
![2016-08-03_21 41 14](https://cloud.githubusercontent.com/assets/12763829/17379595/69a0c8be-59c3-11e6-99f1-41780c8969c5.png)
And when you go walk against an Ender Chest, you get damage until you suffocate in a wall. The Ender Chest needs to be placed at the height of your head to reproduce this.

**Comment by covers1624** [comment]
There is probably another mod messing with rendering stuff, i am unable to reproduce this, if you can reproduce this with as little mods as possible that would be great. I will reopen if you can reproduce it.
