### ISSUE TITLE
Deprecated version of getDrops overridden

### ISSUE THREAD

**Issue by SquidDev** [TheCBProject/EnderStorage#70]
The current implementation of `BlockEnderStorage` overrides the `List<ItemStack> getDrops(IBlockAccess world, BlockPos pos, IBlockState state, int fortune)` method:

https://github.com/TheCBProject/EnderStorage/blob/244ece6b21a1e759b357c2b59b9ecc5aeb442cd9/src/main/java/codechicken/enderstorage/block/BlockEnderStorage.java#L97

However, this overload is deprecated, one should instead override `public void getDrops(NonNullList<ItemStack> drops, IBlockAccess world, BlockPos pos, IBlockState state, int fortune)`. This makes it consistent with vanilla blocks such as `BlockLeaves`.

I realise this is a rather petty issue (sorry), but some mods (well, ComputerCraft) calls the latter method, meaning all metadata/NBT was lost when broken with a turtle.

**Comment by covers1624** [comment]
Cheers! Not a petty issue at all!  
I'm gathering the new method was added recently, although i cant remember a pr for it recently. I would have assumed the new method delegated but either way ill add this to the list!
