### ISSUE TITLE
[1.12.2] Cannot put a diamond on the latch of an ender storage chest

### ISSUE THREAD

**Issue by Captainaviator** [TheCBProject/EnderStorage#75]
Nothing happens when right clicking with a diamond on the latch (it just opens the chest), both sneaking an non sneaking. I also tried aiming it at different sides of the latch. I can see the bounding box of the latch.  

I'm running 1.12 now, previous ticket for 1.11: https://github.com/TheCBProject/EnderStorage/issues/45

**Comment by DezziDez** [comment]
This appears to be a graphical bug, You can put and diamond on the latch and take it off. It just doesn't appear. It still acts as a personal chest.

**Comment by gigabit101** [comment]
seems fine to me

![2018-03-06_16-42-38](https://user-images.githubusercontent.com/5615438/37045245-66aa627e-215d-11e8-8e1c-8552c8a5e1b7.gif)

**Comment by covers1624** [comment]
Yeah, this appears to work fine.. Does logging out and logging back in show the chest as locked? I fire a packet as soon as you add the personal item..

**Comment by Captainaviator** [comment]
It turned out the server I was on, was using totems of undying instead of diamonds to personalize ender chests.  It works when using that.  I have not gone back and tested in single player after changing the configs back to default to verify that diamonds work though.

**Comment by covers1624** [comment]
Alright, ill close this for now then, let me know if anything changes.
