### ISSUE TITLE
Error. Exception loading model for variant [MC1.12.2]

### ISSUE THREAD

**Issue by kellixon** [TheCBProject/EnderStorage#78]
Minecraft: 1.12.2
Forge: all (last 14.23.2.2637)
EnderStorage 2.4.2.126
CodeChickenLib 3.1.6.339
Lines:
10871
10894
11016
Debug Log - https://drive.google.com/open?id=17dCrv1l_taOd9Js8wWa6RZbId6PPamuF

**Comment by covers1624** [comment]
These are just missing models, it's safe to ignore them.

**Comment by covers1624** [comment]
Also duplicate.
