### ISSUE TITLE
Crash on minecraft when searching anything enderstorage-tanks related.

### ISSUE THREAD

**Issue by arjove** [TheCBProject/EnderStorage#80]
Minecraft just straight up crashes when searching anything enderstorage-tanks related. 

https://gist.github.com/arjove/41365479fc92a60e2e948f66446c76a7

**Comment by GewoonYorick** [comment]
Same here... Would be nice to see it fixed. Enderstorage mod can't be used atm. It leads to a lot of confusion by the players.

Would be really nice if this gets fixed!

**Comment by covers1624** [comment]
Duplicate of #77
