### ISSUE TITLE
High process time when Ender Chests used with refined storage

### ISSUE THREAD

**Issue by RacerDelux** [TheCBProject/EnderStorage#82]
Not sure where the issue lies, so reporting it in both places. This is the reported process time for the ender chest when hooked to refined storage import buss.
![image](https://user-images.githubusercontent.com/2667344/39932627-475b313c-5506-11e8-961d-44ec4faf43f3.png)
Adding a hopper or any other buffer between the ender chest and the refined storage import buss fixes the issue.

MC 1.12.2 ATM3
https://github.com/raoulvdberge/refinedstorage/issues/1782

**Comment by RacerDelux** [comment]
How would I go about doing this?

**Comment by covers1624** [comment]
https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by covers1624** [comment]
Any luck on that sampler dump?

**Comment by RacerDelux** [comment]
Work has been crazy, have not had the chance to tinker with it =(. I will though!

**Comment by covers1624** [comment]
Progress?
