### ISSUE TITLE
mod causes game to crash.  

### ISSUE THREAD

**Issue by poppciccle** [TheCBProject/EnderStorage#84]
when i try to load minecraft, forge loads th game to about 20% and then it closes and goes to the launcher and i get this error:  

```
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from EnderStorage (enderstorage)
```

i have tried reinstalling the mod but nothing works

**Comment by covers1624** [comment]
Going to need you crash report not the blurb from the native launcher's horrid window.

**Comment by Kuktar** [comment]
you need to update forge. even without a crashlog i know you are not on the new version of forge.

**Comment by poppciccle** [comment]
i installed the latest version of forge just before installing the mod

**Comment by poppciccle** [comment]
[crash-2018-05-29_16.10.54-client.txt](https://github.com/TheCBProject/EnderStorage/files/2059528/crash-2018-05-29_16.10.54-client.txt)

**Comment by covers1624** [comment]
You have the deobf jar installed, the one for mod developers, you want universal.
