### ISSUE TITLE
Ender Pouch Off-Hand Bow

### ISSUE THREAD

**Issue by znxster** [TheCBProject/EnderStorage#88]
I am using EnderStorage v2.4.2.126 in the FC3 modpack.

If I hold a bow in my off-hand and right click, the pouch opens but the bow also draws back. When the pouch closes it fires.

I believe this is specific to the mod item as I also use a Thermal Expansion Satchel. This operates similarly, right click to open an inventory but it does not cause the bow to draw back.

**Comment by covers1624** [comment]
This was fixed, please update your mods before posting issues.
