### ISSUE TITLE
Codechicken core updated - crash

### ISSUE THREAD

**Issue by deathmock5** [TheCBProject/EnderStorage#89]
Think its because code chicken updated. Tried to downgrade still does it, trying to remove mod and then re-enable.

https://pastebin.com/1RYvy9LK

**Comment by deathmock5** [comment]
Removing and re-adding only helps for a time. Better question, why is the server trying to render a particle?
https://github.com/TheCBProject/EnderStorage/blob/df861d61c338a611181c76a7542acfffbe9425c4/src/main/java/codechicken/enderstorage/block/BlockEnderStorage.java#L275 Should it be Sided to client?

**Comment by covers1624** [comment]
Update EnderStorage. I was calling the wrong method. The way landing effects are added is weird, vanilla and the forge hook for landing particles, mean you need to send a packet from the server to all clients watching the chunk to add landing particles, vanilla's block particles are dumb, CCL has a system that is wayy less dumb and allows face & state based particles (hit a TE machine and you get the textures for the face, not just a stupid standard texture.). In EnderStorage i was calling the wrong method, thats all.

**Comment by deathmock5** [comment]
Ah, wow that is weird.
