### ISSUE TITLE
Private Enderchest Diamonds

### ISSUE THREAD

**Issue by Algo-ryth-mix** [TheCBProject/EnderStorage#9]
I managed to create Diamonds using levels and Enderchests

So here is what I did:

1.) crafted a Steel Anvil from Railcraft
2.) put a Enderchest in it
3.) named the Enderchest
4.) pulled it out

*\* I do now have a private Enderchest **

6.) remove the Diamond

*\* I do now have a normal Enderchest + 1 Diamond **

Repeat ... it worked every time

It basically exchanged 5 lvl against a Diamond

I am using the FTB Infinity Pack

**Comment by covers1624** [comment]
That should not be possible, naming an Ender Chest in an anvil should not set the owner unless RailCraft is doing silly things, Anyway, This is on a 1.7.10 version that is considered Legacy at this point which means no support for it.
