### ISSUE TITLE
EnderTank crashed

### ISSUE THREAD

**Issue by mcenderdragon** [TheCBProject/EnderStorage#91]
I switched the output valve and my client and the server crashed. It was connected to a machine from binnie. 

binnie-mods-1.12.2-2.5.0.165.jar
https://hastebin.com/ejazetipos.py

**Comment by mcenderdragon** [comment]
After visiting the code the fault is most likly at binnies.

**Comment by covers1624** [comment]
Yeah this is on binnies, i check for a cap then i get the cap and they return null.

**Comment by covers1624** [comment]
I've made some changes to guard against this.
