### ISSUE TITLE
Suggestion - Ender Bucket

### ISSUE THREAD

**Issue by mopsyd** [TheCBProject/EnderStorage#93]
Just dropping a nice-to-have suggestion. We have the ender pouch to link to an ender chest on the go, which is great, but there is no equivalent item for ender tanks. Perhaps an "ender bucket" that can place from and into a linked ender tank would be a meaningful addition. As this is ostensibly a pretty straightforward mechanic (eg right click to scoop from world, shift right click to place from ender tank into world, etc), it may not even be all that difficult to integrate, although there may be a couple of gotchas involving drinking from an ender milk bucket or crafting recipes that involve buckets of various liquids.

**Comment by Ecu** [comment]
Suggestion has been posted multiple times.  Most recently, it was posted here...
 https://github.com/TheCBProject/EnderStorage/issues/90

I personally am not sure about adding another quick access tool.  I've already seen the pouch heavily abused.  That said, with the pouch existing...it is definitely hard to justify not implementing a bucket.  If it was implemented, I worry that implementing it as a bucket could definitely lead to gotchas and I'm not sure how best to handle those.  That would be something for @covers1624 to handle though.

**Comment by covers1624** [comment]
Im still not sure on this one, i might mess with this during the 1.13 port.

**Comment by covers1624** [comment]
This will not be happening sorry.
