### ISSUE TITLE
[1.12.2] Crash when looking up recipe

### ISSUE THREAD

**Issue by ProxyPlayerHD** [TheCBProject/EnderStorage#94]
was looking through the craftring recipes of chests in JEI until i hit the page with some item from Ender Storage. game instantly crashed with this log:
[LOG](https://pastebin.com/8GmMXkSB)
Log should contain all information needed

EDIT: actually now that i tested a bit it also happens with Chicken chunks with the same error

**Comment by covers1624** [comment]
Backdate forge, apparently some new changes are breaking things..

**Comment by ProxyPlayerHD** [comment]
how far back? can you name a version?

**Comment by covers1624** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/5170 Was just fixed in forge. Update to the very latest, or back a few builds.

**Comment by ProxyPlayerHD** [comment]
it works, thanks!
