### ISSUE TITLE
Suggestion: Mods ender chests emit ender particles like vanilla chests

### ISSUE THREAD

**Issue by mser7** [TheCBProject/EnderStorage#96]
Video showcasing the chest
https://m.youtube.com/watch?v=DzqktEa2pHM

**Comment by Ecu** [comment]
My stance on this is quite simple...Ender Storage is not vanilla.  Ender Chests in Ender Storage already have their own special effect when opening them.  I see no reason to add an additional effect to our Ender Chests.

**Comment by covers1624** [comment]
I'm fine adding a config for this that is dissabled by default, it's not something everyone wants.

**Comment by Ecu** [comment]
@mser7 Ender Storage wasn't based on vanilla Ender Chests at all, I created Ender Storage before vanilla Ender Chests even existed.  As for why I'm against it, there is just no reason to add such a thing.  Ender Storage already has their own special effects.  Adding vanilla special effects on top of it is just adding clutter.  So my stance is still no.

@covers1624 If you want to do that, I suppose that is up to you.  I am not fond of adding more special effects for the sake of adding more special effects.  I actually feel this could end up creating confusion between the vanilla and mod Ender Chests as well.

**Comment by covers1624** [comment]
I'm inclined to agree with you now, this won't be happening.

**Comment by mser7** [comment]
My bad, I didn't aware that this mod was created before the vanilla ender chest. I have another question however, then does that mean vanilla ender chest mechanic is inspired by ender storage?

**Comment by Ecu** [comment]
@mser7 I don't believe so, no.  From what I understand, around the time I created Ender Storage, someone else had suggested vanilla Ender Chests on reddit.  I wasn't aware of this happening until years later.  Great minds think alike, I suppose.
