### ISSUE TITLE
Getting Server Tick loop error

### ISSUE THREAD

**Issue by Algester** [TheCBProject/EnderStorage#97]
https://github.com/CoFH/Feedback/issues/1342
this is conjunction with this issue

for further info
https://pastebin.com/9r4xyiap

removing endertanks via MCEdit is hard <_<

**Comment by covers1624** [comment]
Literely not my bug, i advertise that im an IFluidHandler always. As i work on both the mods involved here, im just chocking this down to a rare edgecase, nothing i can do.
